(function(g){var window=this;'use strict';var Uw=function(D){D.publish("cardstatechange",D.JE()&&D.i4()?1:0)},AW=function(D,O){var h=g.r2(O),V=h?O:arguments;
for(h=h?0:1;h<V.length;h++){if(D==null)return;D=D[V[h]]}return D},hEv=function(D){var O=g.Q7(D);
D=g.Wt(D);return new g.RH(O.x,O.y,D.width,D.height)},VEC=function(D,O,h){var V=V===void 0?{}:V;
var k;return k=g.GF(D,O,function(){g.ta(k);h.apply(D,arguments)},V)},vY=function(D){D=g.Zy(D);
delete Gy[D];g.sO(Gy)&&tW&&tW.stop()},CDU=function(){tW||(tW=new g.kF(function(){k89()},20));
var D=tW;D.isActive()||D.start()},k89=function(){var D=g.xw();
g.K2(Gy,function(O){MES(O,D)});
g.sO(Gy)||CDU()},QF=function(D,O,h,V){g.Ld.call(this);
if(!Array.isArray(D)||!Array.isArray(O))throw Error("Start and end parameters must be arrays");if(D.length!=O.length)throw Error("Start and end points must be the same length");this.K=D;this.L=O;this.duration=h;this.J=V;this.coords=[];this.progress=this.Z=0;this.W=null},MES=function(D,O){O<D.startTime&&(D.endTime=O+D.endTime-D.startTime,D.startTime=O);
D.progress=(O-D.startTime)/(D.endTime-D.startTime);D.progress>1&&(D.progress=1);D.Z=1E3/(O-D.W);D.W=O;bbJ(D,D.progress);D.progress==1?(D.D=0,vY(D),D.onFinish(),D.J$()):D.isPlaying()&&D.PL()},bbJ=function(D,O){typeof D.J==="function"&&(O=D.J(O));
D.coords=Array(D.K.length);for(var h=0;h<D.K.length;h++)D.coords[h]=(D.L[h]-D.K[h])*O+D.K[h]},cFJ=function(D,O){g.rj.call(this,D);
this.coords=O.coords;this.x=O.coords[0];this.y=O.coords[1];this.z=O.coords[2];this.duration=O.duration;this.progress=O.progress;this.fps=O.Z;this.state=O.D},wg=function(D,O,h,V,k){QF.call(this,O,h,V,k);
this.element=D},SJJ=function(D,O,h,V,k){if(O.length!=2||h.length!=2)throw Error("Start and end points must be 2D");
wg.call(this,D,O,h,V,k)},YJe=function(D){return Math.pow(D,3)},JFJ=function(D){return 3*D*D-2*D*D*D},qJC=function(D){g.n.call(this);
this.K=D||window;this.D=[]},WY=function(D){return D.baseUrl||null},Ty=function(D,O){return g.LS(g.WS(D,O),function(h){return!!h})},uj_=function(D,O,h){function V(Yw){var B=Yw.hovercardButton;
if(!B)return null;B=B.subscribeButtonRenderer;if(!B)return null;var r=C(B.unsubscribedButtonText),I=C(B.subscribedButtonText);if(B.subscribed){var L=C(B.subscriberCountWithUnsubscribeText);var p=C(B.subscriberCountText)}else L=C(B.subscriberCountText),p=C(B.subscriberCountWithSubscribeText);var Id=null;if(Yw.signinEndpoint){Id=AW(Yw,"signinEndpoint","webNavigationEndpointData","url");if(!Id){var aL,hx;Id=(hx=g.y((aL=B.signInEndpoint)==null?void 0:aL.commandMetadata,g.g4))==null?void 0:hx.url}if(!Id)return null}return r&&
(I||Id)?{subscribed:B.subscribed,subscribeText:r,subscribeCount:L,unsubscribeText:I,unsubscribeCount:p,enabled:B.enabled,signinUrl:Id,classic:Yw.useClassicSubscribeButton}:null}
function k(Yw){if(Yw){var B=[],r=Yw.videoId;r&&B.push("v="+r);(r=Yw.playlistId)&&B.push("list="+r);(Yw=Yw.startTimeSeconds)&&B.push("t="+Yw);return"/watch?"+B.join("&")}}
function C(Yw){if(!Yw)return null;var B=Yw.simpleText;return B?B:Yw.runs?g.WS(Yw.runs,function(r){return r.text}).join(""):null}
O=O.endscreenElementRenderer;if(!O)return null;var M=O.style,c=O.endpoint||{},S=null,Y=null,J=!1,q=null,u=null,H=null,m=null,R=!1,f=null,E=null,A=null,v=null,W=null,z=null;if(M==="VIDEO")g.y(c,g.r8)?S=g.y(c,g.r8).url:(z=g.y(c,g.CO),S=k(z)),Y=!1,q=D,O.thumbnailOverlays?(J=O.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,u=C(J.text),J=J.style==="LIVE"):u=C(O.videoDuration);else if(M==="PLAYLIST")g.y(c,g.r8)?S=g.y(c,g.r8).url:(z=g.y(c,g.CO),S=k(z)),Y=!1,q=D,H=C(O.playlistLength);else if(M===
"CHANNEL"){if(R=AW(c,"browseEndpoint","browseId"))m=R,S="/channel/"+m;Y=!1;q="new";(R=!!O.isSubscribe)?f=V(O):E=C(O.subscribersText)}else M==="WEBSITE"?((A=AW(c,"urlEndpoint","url"))&&(S=A),Y=!0,q="new",A=O.icon.thumbnails[0].url):M==="CREATOR_MERCHANDISE"&&(O.productPrice&&(v=C(O.productPrice)),O.additionalFeesText&&(W=C(O.additionalFeesText)),(Y=AW(c,"urlEndpoint","url"))&&(S=Y),Y=!0,q="new");D=AW(O,"title","accessibility","accessibilityData","label");var X=O.endpoint?O.endpoint.clickTrackingParams:
null,Z="";if(O.metadata){var hd=C(O.metadata);hd&&(Z=hd)}return{id:"element-"+h,type:M,title:C(O.title),metadata:Z,callToAction:C(O.callToAction),KH:O.image,iconUrl:A,left:Number(O.left),width:Number(O.width),top:Number(O.top),aspectRatio:Number(O.aspectRatio),startMs:Math.floor(Number(O.startMs)),endMs:Math.floor(Number(O.endMs)),videoDuration:u,jp:J,playlistLength:H,channelId:m,subscribeButton:f,subscribersText:E,isSubscribe:R,targetUrl:S||null,sW2:Y,sessionData:X?{itct:X}:null,KGF:q,v7:D?D:null,
isPlaceholder:O.isPlaceholder,impressionUrls:Ty(O.impressionUrls||[],WY),v7T:Ty(O.hovercardShowUrls||[],WY),clickUrls:Ty(c.loggingUrls||[],WY),visualElement:g.th(O.trackingParams),productPrice:v,additionalFeesText:W,watchEndpoint:z||null}},Hbv=function(D,O){var h={startMs:Math.floor(Number(D.startMs)),
impressionUrls:Ty(D.impressionUrls||[],WY),elements:Ty(D.elements||[],function(V,k){return uj_(O,V,k)})};
D.trackingParams&&(h.visualElement=g.th(D.trackingParams));return h},mk8=function(D){g.dX.call(this,D);
this.W=this.endscreen=null;this.K={};this.Z={};this.J=this.j=null;this.T=[];this.D=null;this.Ew=!0;this.L=0;D=D.V();this.U=g.Q3(D)||g.sA(D);this.events=new g.yp(this);g.F(this,this.events);this.events.G(this.player,g.J6("creatorendscreen"),this.onCueRangeEnter);this.events.G(this.player,g.q1("creatorendscreen"),this.onCueRangeExit);this.events.G(this.player,"resize",this.PQ);this.events.G(window,"focus",this.B0i);this.load();var O=g.CZ("STYLE");(g.ll("HEAD")[0]||document.body).appendChild(O);this.addOnDisposeCallback(function(){g.Ye(O)});
O.sheet&&(O.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),O.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},eE9=function(D){return D.player.getVideoData().Q$?"current":D.U?"new":"current"},dg=function(D){return D.player.V().playerStyle==="creator-endscreen-editor"},LBR=function(D){var O=D.player.getVideoData(),h=O.videoId;
D.W&&D.W.abort();h={method:"POST",onFinish:function(k){var C=D.W=null;k.status===200&&(k=k.responseText,k.substring(0,3)===")]}"&&(k=k.substring(3),C=JSON.parse(k),C=Hbv(C,eE9(D))));zy(D,C)},
urlParams:{v:h},withCredentials:!0};D.U&&(h.urlParams.ptype="embedded");var V=O.D6;V&&(h.postParams={ad_tracking:V});if(O=g.SXe(O))if(O=g.zs(O),O=g.WF(O))D.W=g.wt(O,h)},zy=function(D,O,h){h=h===void 0?!0:h;
D.player.Y8("creatorendscreen");D.j&&(D.j.dispose(),D.j=null,D.J.dispose(),D.J=null);for(var V=g.P(Object.values(D.K)),k=V.next();!k.done;k=V.next())k.value.dispose();D.K={};D.Z={};D.T.length>0&&(D.T.forEach(function(c){c.dispose()}),D.T.length=0);
D.D&&(g.Hk(D.D,"ytp-ce-element-show"),D.D.setAttribute("aria-hidden","true"));D.L=0;if((D.endscreen=O)&&O.elements){h&&PD9(D);h=[];V=new g.S4(O.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});h.push(V);D.player.V().K||(D.j=new g.N({X:"div",Y:"ytp-ce-shadow"}),g.BR(D.player,D.j.element,4),D.J=new g.bH(D.j,200));for(V=0;V<O.elements.length;++V){k=O.elements[V];var C=gtc(D,k);if(C){D.K[k.id]=C;D.Z[k.id]=k;g.BR(D.player,C.element,4);var M=new g.S4(k.startMs,k.endMs,{id:"ytp-ce-element-"+
k.id,namespace:"creatorendscreen"});h.push(M);REx(D,C,k)}else g.iZ(new g.D3("buildEndscreenElement null",k))}D.player.nW(h);D.PQ()}},PD9=function(D){var O=g.QK(),h=g.w_();
h&&O&&D.endscreen.visualElement&&g.Cc(g.D2)(void 0,h,O,D.endscreen.visualElement)},gtc=function(D,O){var h=null;
switch(O.type){case "VIDEO":D={X:"div",eT:["ytp-ce-element","ytp-ce-video"],B:{tabindex:"0","aria-label":O.v7||"","aria-hidden":"true"},N:[{X:"div",Y:"ytp-ce-element-shadow"},{X:"div",Y:"ytp-ce-covering-image",B:nM(O)},{X:"div",Y:"ytp-ce-covering-shadow-top"},{X:"a",Y:"ytp-ce-covering-overlay",B:{href:FQ(D,O.targetUrl),tabindex:"-1"},N:[{X:"div",eT:["ytp-ce-video-title","ytp-webkit-ellipsis"],B:{dir:g.fd(O.title||"")},W3:O.title},{X:"div",Y:O.jp?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
W3:O.videoDuration||void 0}]}]};h=new g.N(D);break;case "PLAYLIST":D={X:"div",eT:["ytp-ce-element","ytp-ce-playlist"],B:{tabindex:"0","aria-label":O.v7||"","aria-hidden":"true"},N:[{X:"div",Y:"ytp-ce-element-shadow"},{X:"div",Y:"ytp-ce-covering-image",B:nM(O)},{X:"div",Y:"ytp-ce-covering-shadow-top"},{X:"a",Y:"ytp-ce-covering-overlay",B:{href:FQ(D,O.targetUrl),tabindex:"-1"},N:[{X:"div",eT:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],B:{dir:g.fd(O.title||"")},W3:O.title},{X:"div",Y:"ytp-ce-playlist-count",
N:[{X:"div",Y:"ytp-ce-playlist-icon"},{X:"div",Y:"ytp-ce-playlist-count-text",W3:O.playlistLength||void 0}]}]}]};h=new g.N(D);break;case "CHANNEL":h={X:"div",eT:["ytp-ce-element","ytp-ce-channel",O.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],B:{tabindex:"0","aria-label":O.v7||"","aria-hidden":"true"},N:[{X:"div",Y:"ytp-ce-element-shadow"},{X:"div",Y:"ytp-ce-expanding-overlay",N:[{X:"div",Y:"ytp-ce-expanding-overlay-hider"},{X:"div",Y:"ytp-ce-expanding-overlay-background"},{X:"div",Y:"ytp-ce-expanding-overlay-content",
N:[{X:"div",Y:"ytp-ce-expanding-overlay-body",N:[{X:"div",Y:"ytp-ce-expanding-overlay-body-padding",N:[{X:"a",eT:["ytp-ce-channel-title","ytp-ce-link"],B:{href:FQ(D,O.targetUrl),target:"_blank",tabindex:"-1",dir:g.fd(O.title||"")},W3:O.title},O.subscribeButton?{X:"div",Y:"ytp-ce-subscribe-container",N:[{X:"div",Y:"ytp-ce-channel-subscribe"}]}:"",O.subscribersText?{X:"div",Y:"ytp-ce-channel-subscribers-text",W3:O.subscribersText}:"",O.metadata?{X:"div",eT:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],W3:O.metadata}:""]}]}]}]},{X:"div",Y:"ytp-ce-expanding-image",B:nM(O)}]};h=new g.N(h);var V=g.$$(document,"div","ytp-ce-channel-subscribe",h.element)[0];if(O.subscribeButton&&O.channelId){g.qZ(V,"ytp-ce-subscribe-button");if(D.player.V().K){var k=null;var C=O.sessionData.itct}else k="endscreen",C=null;k=new g.eu(O.subscribeButton.subscribeText,O.subscribeButton.subscribeCount,O.subscribeButton.unsubscribeText,O.subscribeButton.unsubscribeCount,!!O.subscribeButton.enabled,!!O.subscribeButton.classic,
O.channelId,!!O.subscribeButton.subscribed,k,C,D.player,!1);V.appendChild(k.element);D.T.push(k)}break;case "WEBSITE":D={X:"div",eT:["ytp-ce-element","ytp-ce-website"],B:{tabindex:"0","aria-label":O.v7||"","aria-hidden":"true"},N:[{X:"div",Y:"ytp-ce-element-shadow"},{X:"div",Y:"ytp-ce-expanding-overlay",N:[{X:"div",Y:"ytp-ce-expanding-overlay-hider"},{X:"div",Y:"ytp-ce-expanding-overlay-background"},{X:"div",Y:"ytp-ce-expanding-overlay-content",N:[{X:"div",Y:"ytp-ce-expanding-overlay-body",N:[{X:"div",
Y:"ytp-ce-expanding-overlay-body-padding",N:[{X:"div",Y:"ytp-ce-website-title",B:{dir:g.fd(O.title||"")},W3:O.title},{X:"div",Y:"ytp-ce-website-metadata",W3:O.metadata},{X:"a",eT:["ytp-ce-website-goto","ytp-ce-link"],B:{href:FQ(D,O.targetUrl),target:"_blank",tabindex:"-1"},W3:O.callToAction}]}]}]}]},{X:"div",Y:"ytp-ce-expanding-image",B:nM(O)},{X:"div",Y:"ytp-ce-expanding-icon",B:aZ_(O.iconUrl)}]};h=new g.N(D);break;case "CREATOR_MERCHANDISE":h="",O.productPrice&&(h={X:"div",Y:"ytp-ce-merchandise-price-container",
N:[{X:"div",Y:"ytp-ce-merchandise-price",W3:O.productPrice}]},O.additionalFeesText&&h.N.push({X:"div",Y:"ytp-ce-merchandise-additional-fees",W3:O.additionalFeesText})),D={X:"div",eT:["ytp-ce-element","ytp-ce-merchandise"],B:{tabindex:"0","aria-label":O.v7||"","aria-hidden":"true"},N:[{X:"div",Y:"ytp-ce-element-shadow"},{X:"div",Y:"ytp-ce-expanding-overlay",N:[{X:"div",Y:"ytp-ce-expanding-overlay-hider"},{X:"div",Y:"ytp-ce-expanding-overlay-background"},{X:"div",Y:"ytp-ce-expanding-overlay-content",
N:[{X:"div",Y:"ytp-ce-expanding-overlay-body",N:[{X:"div",Y:"ytp-ce-expanding-overlay-body-padding",N:[{X:"div",Y:"ytp-ce-merchandise-title",B:{dir:g.fd(O.title||"")},W3:O.title},h,{X:"div",Y:"ytp-ce-merchandise-metadata",W3:O.metadata},{X:"a",eT:["ytp-ce-merchandise-goto","ytp-ce-link"],B:{href:FQ(D,O.targetUrl),target:"_blank",tabindex:"-1"},W3:O.callToAction}]}]}]}]},{X:"div",Y:"ytp-ce-expanding-image",B:nM(O)},{X:"div",Y:"ytp-ce-merchandise-invideo-cta-container",N:[{X:"div",Y:"ytp-ce-merchandise-invideo-cta",
W3:O.callToAction||void 0}]}]},h=new g.N(D)}O.isPlaceholder&&g.qZ(h.element,"ytp-ce-placeholder");return h},nM=function(D){if(D.KH)var O=D.KH.thumbnails;
return aZ_(O?O[O.length-1].url:null)},aZ_=function(D){return D?{style:"background-image: url("+D+")"}:{}},REx=function(D,O,h){function V(S){S&&(O.listen("blur",function(){S.style.display!="none"&&D.Ew&&S.focus()}),O.G(S,"focus",C),O.G(S,"blur",M))}
function k(S){D.L+=S;D.L>0?(g.qZ(O.element,"ytp-ce-force-expand"),yF(D,h.id,!0)):(g.Hk(O.element,"ytp-ce-force-expand"),g.Hk(O.element,"ytp-ce-element-hover"),yF(D,h.id,!1))}
function C(){k(1)}
function M(){k(-1)}
O.listen("mouseenter",function(){fZe(D,O,h)});
O.listen("mouseleave",function(){KB0(D,O,h)});
D.player.V().K||O.listen("click",function(){g.qZ(O.element,"ytp-ce-element-hover")});
O.listen("click",function(S){Etc(D,h,S)});
O.listen("keypress",function(S){Etc(D,h,S)});
O.listen("focus",function(){fZe(D,O,h)});
O.listen("blur",function(){KB0(D,O,h)});
O.listen("touchstart",function(){fZe(D,O,h)});
var c=g.Io("ytp-ce-expanding-overlay-hider",O.element);c&&O.G(c,"touchstart",function(S){S.stopPropagation();g.Hk(O.element,"ytp-ce-element-hover");g.Hk(O.element,"ytp-ce-force-expand")});
O.listen("keydown",function(S){D.Ew=S.keyCode===9&&!S.shiftKey});
V(g.Io("ytp-sb-subscribe",O.element));V(g.Io("ytp-sb-unsubscribe",O.element));O.listen("focus",C);O.listen("blur",M)},Etc=function(D,O,h){if(O.targetUrl&&(!h||h.type!=="keypress"||h.keyCode===13)){for(var V=h.target;V&&!g.JX(V,"ytp-ce-element");){g.JX(V,"subscribe-label")&&jj_(D,O);
if(g.JX(V,"ytp-ce-channel-subscribe"))return;V=V.parentElement||null}if(!V||g.JX(V,"ytp-ce-element-hover")){h.preventDefault();h.stopPropagation();if(V=D.K[O.id])KB0(D,V,O),V.element.blur();if(h.ctrlKey||h.metaKey||O.KGF==="new")jj_(D,O),D.player.sendVideoStatsEngageEvent(17,void 0),D.player.pauseVideo(),h=g.zs(FQ(D,O.targetUrl)),h=g.WF(h),g.lH(h,void 0,O.sessionData);else{var k=g.Z$(D.player.V())||D.player.getVideoData().Q$,C=function(){var M=FQ(D,O.targetUrl),c=O.sessionData,S=O.watchEndpoint,Y=
g.JO(M);k&&Y&&(Y.v||Y.list)?D.player.d5(Y.v,c,Y.list,!1,void 0,S||void 0):g.Bi(M,c)};
jj_(D,O,function(){D.player.sendVideoStatsEngageEvent(17,C)})}}}},FQ=function(D,O){D=D.player.V();
if(O){if(O.startsWith("//"))return D.protocol+":"+O;if(O.startsWith("/"))return g.OK(D)+O}else return"";return O},fZe=function(D,O,h){g.JX(O.element,"ytp-ce-element-hover")||(h.type==="VIDEO"||h.type==="PLAYLIST"?g.qZ(O.element,"ytp-ce-element-hover"):D.player.V().K?(new g.kF(function(){g.qZ(O.element,"ytp-ce-element-hover")},200)).start():g.qZ(O.element,"ytp-ce-element-hover"),i7(D,h.v7T),yF(D,h.id,!0))},KB0=function(D,O,h){g.Hk(O.element,"ytp-ce-element-hover");
g.Hk(O.element,"ytp-ce-force-expand");yF(D,h.id,!1)},yF=function(D,O,h){D.j&&(h?D.J.show():D.J.hide());
for(var V=g.P(Object.keys(D.K)),k=V.next();!k.done;k=V.next())k=k.value,k!==O&&g.eX(D.K[k].element,"ytp-ce-element-shadow-show",h)},i7=function(D,O,h){function V(){C||(k++,k===O.length&&(M.stop(),h&&h()))}
if(!O||O.length===0||dg(D))h&&h();else{O=UkU(D,O);var k=0,C=!1,M=new g.kF(function(){C=!0;h&&h()},1E3,D);
M.start();for(D=0;D<O.length;D++)g.IB(O[D],V)}},jj_=function(D,O,h){i7(D,O.clickUrls,h);
(D=g.w_())&&O.sW2&&g.JA(D,O.visualElement)},UkU=function(D,O){var h=D.player.getVideoData().clientPlaybackNonce;
D=D.player.getCurrentTime().toFixed(2);h={CPN:h,AD_CPN:h,MT:D};D=[];for(var V=0;V<O.length;V++)D.push(AFJ(O[V],h));return D},AFJ=function(D,O){return D.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(h){var V=unescape(h);
V=V.substring(1,V.length-1);return O[V]?escape(O[V]):h})},G88=function(D){return typeof D==="string"?D:""},rg=function(D,O,h){for(var V in O)if(O[V]===D)return D;
return h},tE_=function(D,O,h,V){this.value=D;
this.target=O;this.showLinkIcon=h;this.D=V},pM=function(D){return D.value?D.value:null},Nb=function(D){if(!D)return null;
var O=g.zs(G88(D.value));O=g.WF(O);if(!O)return null;var h=rg(D.target,vtL,"current");if(h==null)D=null;else{var V=D.show_link_icon;D=new tE_(O,h,V==="true"||V==="false"?V==="true":!0,D.pause_on_navigation!=null?D.pause_on_navigation:!0)}return D},QjJ=function(D,O,h){this.type=D;
this.trigger=O;this.url=h},WBc=function(D){if(!D)return null;
var O=rg(D.type,w8L),h=rg(D.trigger,sjv);D=D.url;D=Array.isArray(D)&&D.length?D[0]:D;D=Nb(D?D:null);return O?new QjJ(O,h,D):null},TQ0=function(D,O,h,V,k){this.id=D;
this.type=O;this.style=h;this.data=k;this.action=V||[]},dkR=function(D,O){return g.Zm(D.action,O)},zEe=function(D,O){this.context=D;
this.D=O},ntC=function(D){return D.customMessage?oq("div","iv-card-message",D.customMessage):""},ZG=function(D,O){D="background-image: url("+D+");";
var h=[];O&&h.push(O);return{X:"div",Y:"iv-card-image",B:{style:D},N:h}},FBR=function(D){if(!D.metaInfo||D.metaInfo.length===0)return"";
var O=[];D=g.P(D.metaInfo);for(var h=D.next();!h.done;h=D.next())O.push(oq("li","",h.value));return{X:"ul",Y:"iv-card-meta-info",N:O}},oq=function(D,O,h){O?typeof O==="string"?O={"class":O}:Array.isArray(O)&&(O={"class":O.join(" ")}):O={};
O.dir=g.fd(h);return{X:D,B:O,W3:h}},yFJ=function(D){if(!D.customMessage)return"";
var O=["iv-card-action","iv-card-primary-link"],h={};D.hw&&(O.push("iv-card-action-icon"),h.style="background-image: url("+D.hw+");");h.dir=g.fd(D.customMessage);var V=[{X:"span",W3:D.customMessage}];D.showLinkIcon&&(V.push("\u00a0"),V.push({X:"span",Y:"iv-card-link-icon"}));return{X:"div",eT:O,B:h,N:V}},XQ=function(D,O,h,V){if(V){O=g.P(O);
for(var k=O.next();!k.done;k=O.next())D.D(k.value,V,h.id,h.sessionData,h.CO.click,5)}},ibR=function(D,O){this.merchant=D;
this.price=O},rFR=function(D){var O;
(O=D)&&!(O=D.length>1?D.charAt(0)==="/"&&D.charAt(1)!=="/":D==="/")&&(O=D.replace(/^(https?:)?\/\//,"").split("/",1),O=!O||O.length<1||!O[0]?[]:O[0].toLowerCase().split(".").reverse(),O=O[0]==="com"&&O[1]==="youtube"||O[0]==="be"&&O[1]==="youtu");return O?D.indexOf("/redirect?")===-1:!1},p8S=function(D,O){return O?O:rFR(D)?"current":"new"},BY=function(D,O){g.n.call(this);
var h=this;this.element=D;this.context=O;this.m5=!1;this.Vi=new Map;this.Ax=new Map;this.context.C.addEventListener(g.J6("annotations_module"),function(V){(V=h.Vi.get(V))&&V.apply(h)});
this.context.C.addEventListener(g.q1("annotations_module"),function(V){(V=h.Ax.get(V))&&V.apply(h)})},l7=function(D,O,h,V,k,C,M){D.context.D.listen(O,"click",function(c){D.fq(h,V,k,C||[],M||0,c)});
D.context.D.listen(O,"touchstart",function(){D.m5=!1});
D.context.D.listen(O,"touchmove",function(){D.m5=!0})},NQx=function(D){var O;
return((O=g.y(D,g.r8))==null?0:O.url)?g.y(D,g.r8).url:(D=g.y(D,g.CO))&&D.videoId?(O="/watch?v="+D.videoId,D.playlistId&&(O+="&list="+D.playlistId),D.index&&(O+="&index="+D.index),D.startTimeSeconds&&(O+="&t="+D.startTimeSeconds),O):null},xr=function(D,O,h){return{xp:(D.impressionLoggingUrlsV2s||[]).map(function(V){return V.baseUrl||""}),
click:(h.loggingUrls||[]).map(function(V){return V.baseUrl||""}),
close:(O.dismissLoggingUrlsV2s||[]).map(function(V){return V.baseUrl||""}),
Md:(O.impressionLoggingUrlsV2s||[]).map(function(V){return V.baseUrl||""}),
gi:(O.clickLoggingUrlsV2s||[]).map(function(V){return V.baseUrl||""})}},otR=function(D,O,h){BY.call(this,O,h);
var V=this;this.C=D;this.eventId=null;this.f1=this.ST=this.C1=this.j=this.isInitialized=!1;this.cards=[];this.Uw=this.T=this.ME=this.J=this.G2=this.D=null;this.Ew=[];this.jT=this.L=this.Pa=this.X1=null;this.Z=0;this.qE=new g.kF(function(){},h.D8.Id?4E3:3E3);
g.F(this,this.qE);this.oW=new g.kF(function(){});
g.F(this,this.oW);this.lS=new zEe(h,function(k,C,M,c,S,Y){l7(V,k,C,M,c,S,Y)});
this.U=new g.N({X:"div",Y:"iv-drawer",B:{id:"iv-drawer"},N:[{X:"div",Y:"iv-drawer-header",B:{"aria-role":"heading"},N:[{X:"span",Y:"iv-drawer-header-text"},{X:"button",eT:["iv-drawer-close-button","ytp-button"],B:{"aria-label":"Hide cards",tabindex:"0"}}]},{X:"div",Y:"iv-drawer-content"}]});g.F(this,this.U);this.W=this.U.element;this.T2=new g.bH(this.U,330);g.F(this,this.T2);this.yy=g.Io("iv-drawer-header-text",this.W);this.K=g.Io("iv-drawer-content",this.W);this.addCueRange(0,h.videoData.lengthSeconds*
1E3,"",function(){V.C1&&$r(V,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(V.C1=V.j)&&Iq(V)});
this.LF=new g.yp(this);g.F(this,this.LF);this.C.addEventListener("videodatachange",this.PR.bind(this))},Zb8=function(D,O){O=O.data;
O.autoOpenMs&&D.addCueRange(O.autoOpenMs,0x8000000000000,"",function(){$r(D,"YOUTUBE_DRAWER_AUTO_OPEN")});
O.autoCloseMs&&D.addCueRange(O.autoCloseMs,0x8000000000000,"",function(){Iq(D)});
var h=O.headerText;g.qf(D.yy,h);D.T&&D.T.setAttribute("title",h);O.eventId&&(D.eventId=O.eventId);D.X1=g.th(O.trackingParams);D.L=g.th(O.closeTrackingParams);D.Pa=g.th(O.iconTrackingParams)},X8C=function(D,O){var h=O.cardId?O.cardId:"cr:"+D.Z,V=D.C.V().experiments.P3("enable_error_corrections_infocard_web_client");
if(!O.content&&O.teaser.simpleCardTeaserRenderer&&V){var k=O.teaser.simpleCardTeaserRenderer,C=O.icon?O.icon.infoCardIconRenderer:null;O={id:h,timestamp:D.Z,type:"simple",teaserText:g.fl(k.message),teaserDurationMs:Number(O.cueRanges[0].teaserDurationMs),startMs:Number(O.cueRanges[0].startCardActiveMs),autoOpen:!!O.autoOpen,sessionData:{},sponsored:!1,CO:{},ON:null,Qs:k.trackingParams?g.th(k.trackingParams):null,Pa:C&&C.trackingParams?g.th(C.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
hw:null,title:"",customMessage:"",url:null,onClickCommand:k.onTapCommand||null};D5(D,O)}else{var M;if((M=O.content)==null?0:M.simpleCardContentRenderer){if(!O.cueRanges.length)return;C=(k=O.content)==null?void 0:k.simpleCardContentRenderer;k=O.teaser.simpleCardTeaserRenderer;var c=O.icon?O.icon.infoCardIconRenderer:null;O={id:h,timestamp:D.Z,type:"simple",teaserText:g.fl(k.message),teaserDurationMs:Number(O.cueRanges[0].teaserDurationMs),startMs:Number(O.cueRanges[0].startCardActiveMs),autoOpen:!!O.autoOpen,
sessionData:Ov(D,h,O,C),sponsored:!1,CO:xr(C,k,C.command),ON:C.trackingParams?g.th(C.trackingParams):null,Qs:k.trackingParams?g.th(k.trackingParams):null,Pa:c&&c.trackingParams?g.th(c.trackingParams):null,imageUrl:hm(C.image.thumbnails,290).url,displayDomain:C.displayDomain?g.fl(C.displayDomain):null,showLinkIcon:!!C.showLinkIcon,hw:null,title:C.title?g.fl(C.title):"",customMessage:C.callToAction?g.fl(C.callToAction):"",url:g.y(C.command,g.r8).url?Nb({pause_on_navigation:!D.context.videoData.isLivePlayback,
target:"new",value:g.y(C.command,g.r8).url}):null,onClickCommand:null};D5(D,O)}else{var S;if((S=O.content)==null?0:S.collaboratorInfoCardContentRenderer){if(!O.cueRanges.length)return;k=(C=O.content)==null?void 0:C.collaboratorInfoCardContentRenderer;C=O.teaser.simpleCardTeaserRenderer;c=O.icon?O.icon.infoCardIconRenderer:null;O={id:h,timestamp:D.Z,type:"collaborator",teaserText:g.fl(C.message),teaserDurationMs:Number(O.cueRanges[0].teaserDurationMs),startMs:Number(O.cueRanges[0].startCardActiveMs),
autoOpen:!!O.autoOpen,sessionData:Ov(D,h,O,k),sponsored:!1,CO:xr(k,C,k.endpoint),ON:k.trackingParams?g.th(k.trackingParams):null,Qs:C.trackingParams?g.th(C.trackingParams):null,Pa:c&&c.trackingParams?g.th(c.trackingParams):null,channelId:g.y(k.endpoint,g.jG).browseId,customMessage:k.customText?g.fl(k.customText):null,profileImageUrl:hm(k.channelAvatar.thumbnails,290).url,title:k.channelName?g.fl(k.channelName):"",metaInfo:[k.subscriberCountText?g.fl(k.subscriberCountText):""],url:Nb({pause_on_navigation:!D.context.videoData.isLivePlayback,
target:"new",value:g.y(k.endpoint,g.jG).canonicalBaseUrl?g.y(k.endpoint,g.jG).canonicalBaseUrl:"/channel/"+g.y(k.endpoint,g.jG).browseId}),onClickCommand:null};D5(D,O)}else{var Y;if((Y=O.content)==null?0:Y.playlistInfoCardContentRenderer){if(!O.cueRanges.length)return;k=(c=O.content)==null?void 0:c.playlistInfoCardContentRenderer;C=O.teaser.simpleCardTeaserRenderer;c=O.icon?O.icon.infoCardIconRenderer:null;O={id:h,timestamp:D.Z,type:"playlist",teaserText:g.fl(C.message),teaserDurationMs:Number(O.cueRanges[0].teaserDurationMs),
startMs:Number(O.cueRanges[0].startCardActiveMs),autoOpen:!!O.autoOpen,sessionData:Ov(D,h,O,k),sponsored:!1,CO:xr(k,C,k.action),ON:k.trackingParams?g.th(k.trackingParams):null,Qs:C.trackingParams?g.th(C.trackingParams):null,Pa:c&&c.trackingParams?g.th(c.trackingParams):null,sI:hm(k.playlistThumbnail.thumbnails,258).url,customMessage:k.customMessage?g.fl(k.customMessage):null,playlistVideoCount:g.fl(k.playlistVideoCount),title:k.playlistTitle?g.fl(k.playlistTitle):"",metaInfo:[k.channelName?g.fl(k.channelName):
"",k.videoCountText?g.fl(k.videoCountText):""],url:Nb({pause_on_navigation:!D.context.videoData.isLivePlayback,target:"new",value:NQx(k.action)}),onClickCommand:null};D5(D,O)}else{var J;if((J=O.content)==null?0:J.videoInfoCardContentRenderer){if(!O.cueRanges.length)return;var q;k=(q=O.content)==null?void 0:q.videoInfoCardContentRenderer;C=O.teaser.simpleCardTeaserRenderer;c=O.icon?O.icon.infoCardIconRenderer:null;O={id:h,timestamp:D.Z,type:"video",teaserText:g.fl(C.message),teaserDurationMs:Number(O.cueRanges[0].teaserDurationMs),
startMs:Number(O.cueRanges[0].startCardActiveMs),autoOpen:!!O.autoOpen,sessionData:Ov(D,h,O,k),sponsored:!1,CO:xr(k,C,k.action),ON:k.trackingParams?g.th(k.trackingParams):null,Qs:C.trackingParams?g.th(C.trackingParams):null,Pa:c&&c.trackingParams?g.th(c.trackingParams):null,sI:hm(k.videoThumbnail.thumbnails,258).url,videoDuration:k.lengthString?g.fl(k.lengthString):null,customMessage:k.customMessage?g.fl(k.customMessage):null,title:k.videoTitle?g.fl(k.videoTitle):"",metaInfo:[k.channelName?g.fl(k.channelName):
"",k.viewCountText?g.fl(k.viewCountText):""],isLiveNow:!!k.badge,url:Nb({pause_on_navigation:!D.context.videoData.isLivePlayback,target:"new",value:NQx(k.action)}),onClickCommand:null};D5(D,O)}}}}}D.Z++},hm=function(D,O){for(var h=-1,V=-1,k=0;k<D.length;k++){if(D[k].height===O||D[k].width===290)return D[k];
((D[k].height||0)<O||(D[k].width||0)<290)&&(h<0||(D[h].height||0)<(D[k].height||0)||(D[h].width||0)<(D[k].width||0))?h=k:((D[k].height||0)>=O||(D[k].width||0)>=290)&&(V<0||(D[V].height||0)>(D[k].height||0)||(D[V].width||0)>(D[k].width||0))&&(V=k)}return D[V>=0?V:h]},Ov=function(D,O,h,V){return{feature:h.feature?h.feature:"cards",
src_vid:D.context.videoData.videoId,annotation_id:O,ei:D.context.videoData.eventId||"",itct:V.trackingParams||""}},lZx=function(D,O){if(O=BQS(D,O))O===D.D&&(D.D=null),D.C.removeCueRange(O.pG.id),g.Ye(O.RN),g.xC(D.cards,O),D.AP(),VH(D)},$r=function(D,O,h){if(!D.j){D.T2.show();
D.G2=new g.kF(function(){g.qZ(D.context.C.getRootNode(),g.pI.IV_DRAWER_OPEN)},0);
D.G2.start();D.LF.G(D.K,"mousewheel",function(M){D.qE.start();M.preventDefault();M=M||window.event;var c=0;M.type=="MozMousePixelScroll"?c=0==(M.axis==M.HORIZONTAL_AXIS)?M.detail:0:window.opera?c=M.detail:c=M.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?M.wheelDeltaY/-30:M.wheelDeltaY/-1.2:M.wheelDelta/-1.6:M.wheelDeltaY/-3;if(M=c)D.K.scrollTop+=M});
D.j=!0;var V=g.w_();V&&D.X1&&D.L&&g.Sg(V,[D.X1,D.L]);O={TRIGGER_TYPE:O};for(var k=g.P(D.cards),C=k.next();!C.done;C=k.next())C=C.value,C.xT||(C.xT=!0,xkR(D.context.logger,C.pG.CO.xp,O)),V&&g.Sg(V,[C.pG.ON]);Uw(D.C);h&&(D.J=new g.kF(function(){D.ME=D.T;D.Uw.focus()},330),D.J.start())}},Iq=function(D){D.j&&(D.T2.hide(),g.d6(D.LF),g.Hk(D.context.C.getRootNode(),g.pI.IV_DRAWER_OPEN),D.j=!1,Uw(D.C),D.J&&D.J.stop(),D.J=new g.kF(function(){D.ME&&(D.ME.focus(),D.ME=null)},330),D.J.start())},$ke=function(D){g.uY(D.JU(),
[g.pI.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.BR(D.C,D.W,5);D.Mf();D.T=g.Io("ytp-cards-button",D.C.getRootNode());D.Uw=g.Io("iv-drawer-close-button",D.W);D.isInitialized=!0},IZe=function(D){D.Ew.push(g.LY("iv-teaser-shown",D.zT,D));
D.Ew.push(g.LY("iv-teaser-hidden",D.o71,D));D.Ew.push(g.LY("iv-teaser-clicked",D.q$,D));D.f1=!0},DlR=function(D,O){var h;
return O.onClickCommand&&((h=g.y(O.onClickCommand,g.TUR))==null?void 0:h.targetId)==="engagement-panel-error-corrections"?(D.jT=O,!0):!1},Oi_=function(D,O){D.jT=O;
var h=D.C.getVideoData();if(!h)return!1;h=g.K1(h);if(h==null?0:h.markersMap)for(var V,k=0;((V=h)==null?void 0:V.markersMap.length)>k;k++){var C=void 0,M=(C=h)==null?void 0:C.markersMap[k];if(M.key==="ERROR_CORRECTION_MARKERS"&&(C=void 0,(M=(C=M.value)==null?void 0:C.markers)&&M.length>0))return V=void 0,O.startMs=((V=g.y(M[0],g.grd))==null?void 0:V.timeRangeStartMillis)||0,D.jT=null,!0}return!1},D5=function(D,O){if(!DlR(D,O)||Oi_(D,O)){var h=hPc(D,O);
if(h){var V={pG:O,RN:h.element,xT:!1};if(O.onClickCommand)D.C.S("web_infocards_teaser_show_logging_fix")&&(D.f1||IZe(D),lZx(D,O.id),h=D.findLastIndex(V),g.VL(D.cards,h,0,V));else{D.isInitialized||$ke(D);lZx(D,O.id);var k=D.findLastIndex(V);g.VL(D.cards,k,0,V);h.CF(D.K,k);D.AP()}O.autoOpen?D.addCueRange(O.startMs,0x8000000000000,O.id,function(){D.j||(D.D=V,VH(D),fL0(D,V),$r(D,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(h=D.context.C.getCurrentTime()*1E3,h<5E3&&h>O.startMs&&KeL(D,V),D.addCueRange(O.startMs,
O.startMs+1,O.id,function(){KeL(D,V)}),VH(D))}}},hPc=function(D,O){switch(O.type){case "simple":D=D.lS;
var h=O.displayDomain?{X:"div",Y:"iv-card-image-text",W3:O.displayDomain}:void 0;var V=yFJ(O);h={X:"div",eT:["iv-card"],N:[{X:"a",Y:"iv-click-target",B:{href:O.url?pM(O.url)||"":""},N:[ZG(O.imageUrl,h),{X:"div",Y:"iv-card-content",N:[oq("h2",void 0,O.title),V]}]}]};h=new g.N(h);XQ(D,g.x$("iv-click-target",h.element),O,O.url);O=h;break;case "collaborator":D=D.lS;h={X:"div",eT:["iv-card","iv-card-channel"],N:[{X:"a",eT:["iv-click-target"],B:{href:pM(O.url)||"","data-ytid":O.channelId},N:[ZG(O.profileImageUrl),
{X:"div",Y:"iv-card-content",N:[ntC(O),{X:"h2",Y:"iv-card-primary-link",W3:O.title},FBR(O)]}]}]};h=new g.N(h);XQ(D,g.x$("iv-click-target",h.element),O,O.url);O=h;break;case "playlist":D=D.lS;h={X:"div",eT:["iv-card","iv-card-playlist"],N:[{X:"a",Y:"iv-click-target",B:{href:pM(O.url)||""},N:[ZG(O.sI,{X:"div",Y:"iv-card-image-overlay",N:[{X:"span",Y:"iv-card-playlist-video-count",W3:O.playlistVideoCount}]}),{X:"div",Y:"iv-card-content",N:[ntC(O),oq("h2","iv-card-primary-link",O.title),FBR(O)]}]}]};
h=new g.N(h);XQ(D,g.x$("iv-click-target",h.element),O,O.url);O=h;break;case "productListing":D=D.lS;var k=O.offers.length!=0;h=["iv-card"];V="";var C=yFJ(O);k&&(h.push("iv-card-product-listing"),V="iv-card-primary-link",C=O.offers[0],k=[],C.price&&k.push({X:"div",Y:"iv-card-offer-price",W3:C.price}),C.merchant&&k.push({X:"div",Y:"iv-card-offer-merchant",W3:C.merchant}),C={X:"div",N:k});k=O.url?pM(O.url)||"":"";h={X:"div",eT:h,B:{tabindex:"0"},N:[{X:"a",eT:["iv-card-image","iv-click-target"],B:{style:"background-image: url("+
O.imageUrl+");",href:k,"aria-hidden":"true",tabindex:"-1"}},{X:"div",Y:"iv-card-content",N:[O.sponsored?{X:"div",Y:"iv-card-sponsored",N:["Sponsored",{X:"div",Y:"iv-ad-info-container",N:[{X:"div",Y:"iv-ad-info",W3:"{{adInfo}}"},{X:"div",Y:"iv-ad-info-icon-container",N:[{X:"div",Y:"iv-ad-info-icon"},{X:"div",Y:"iv-ad-info-callout"}]}]}]}:"",{X:"a",Y:"iv-click-target",B:{href:k},N:[oq("h2",V,O.title),C]}]}]};h=new g.N(h);V=g.CZ("span");g.qf(V,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
h.PF(V,"adInfo");XQ(D,g.x$("iv-click-target",h.element),O,O.url);O=h;break;case "video":D=D.lS;V=O.videoDuration?{X:"span",Y:"iv-card-video-duration",W3:O.videoDuration}:void 0;C=O.isLiveNow?{X:"span",eT:["yt-badge","yt-badge-live"],W3:"LIVE NOW"}:null;k={X:"div",eT:["iv-card","iv-card-video"],N:[{X:"a",Y:"iv-click-target",B:{href:((h=O.url)==null?void 0:pM(h))||""},N:[ZG(O.sI,V),{X:"div",Y:"iv-card-content",N:[ntC(O),oq("h2","iv-card-primary-link",O.title),FBR(O),C]}]}]};h=new g.N(k);XQ(D,g.x$("iv-click-target",
h.element),O,O.url);O=h;break;default:return null}return O},E2R=function(D){if(D.D)return D.D.pG.type==="productListing";
if(D.C.S("enable_wn_infocards")){var O;return!((O=D.cards)==null||!O.length)&&g.Tp(D.cards,function(h){return h.pG.type==="productListing"})}return g.Tp(D.cards,function(h){return h.pG.type==="productListing"})},VH=function(D){g.eX(D.C.getRootNode(),"ytp-cards-shopping-active",E2R(D))},KeL=function(D,O){if(!g.JX(D.C.getRootNode(),"ytp-cards-teaser-shown")){if(D.D!==O){var h=g.w_(),V=D.D?D.D.pG.Pa:D.Pa;
h&&V&&g.YR(h,[V]);D.D=O;VH(D)}(h=D.isInitialized&&D.JU().style.display=="none")||(h=D.context.C.getPlayerState(),V=h===0&&D.context.C.getCurrentTime()===0,h=!(h===1||h===3||V));h||O.pG.teaserDurationMs&&D.C.W_(!0,{teaserText:O.pG.teaserText,durationMs:O.pG.teaserDurationMs,onClickCommand:O.pG.onClickCommand});D.oW.isActive()||((!D.j||!D.qE.isActive()&&D.ST)&&fL0(D,O),D.oW.start(910+O.pG.teaserDurationMs))}},fL0=function(D,O){D.U.WQ?(O=new QF([0,
D.K.scrollTop],[0,O.RN.offsetTop],600,JFJ),D.context.j.listen(O,"animate",function(h){D.K.scrollTop=h.y}),D.context.j.listen(O,"finish",function(h){D.K.scrollTop=h.y}),O.play()):(D.U.Dn(!0),D.K.scrollTop=O.RN.offsetTop,D.U.Dn(!1))},kQ=function(D){return D.D&&D.D.pG?D.D.pG:D.cards[0]&&D.cards[0].pG?D.cards[0].pG:null},BQS=function(D,O){return g.Zm(D.cards,function(h){return h.pG.id===O})},C$=function(D,O,h){BY.call(this,D,O);
this.annotation=h;this.isActive=!1},jUR=function(D){var O=D.annotation.data;
"start_ms"in O&&"end_ms"in O&&D.addCueRange(Number(O.start_ms),Number(O.end_ms),D.annotation.id,function(){D.show()},function(){D.hide()})},ME=function(D,O,h){C$.call(this,D,O,h);
this.K=null;this.L=!1;this.j=null;this.W=!1;this.D=this.Z=this.J=null},UlL=function(D,O){var h=h===void 0?0:h;
var V=hEv(O).width;g.tu(O,V);h=new SJJ(O,[V,O.offsetTop],[V-V-h,O.offsetTop],200,YJe);g.F(D,h);D.context.j.listen(h,"begin",function(){g.TO(O,!0)});
h.play()},tD0=function(D,O){if(O.channel_name){var h=D.createElement({X:"div",
eT:["iv-branding-context-name"],W3:O.channel_name}),V=D.createElement({X:"div",eT:["iv-branding-context-subscribe"]}),k=O.standalone_subscribe_button_data;k&&(D.D=new g.eu(k.subscribeText,k.subscribeCount,k.unsubscribeText,k.unsubscribeCount,!!k.enabled,!!k.classic,O.channel_id,!!k.subscribed,k.feature,O.session_data.itct,D.context.C,!1),D.D.CF(V));var C=D.createElement({X:"div",eT:["iv-branding-context-subscribe-caret"]}),M=D.createElement({X:"div",eT:["branding-context-container-inner"]});M.appendChild(C);
M.appendChild(h);M.appendChild(V);g.TO(M,!1);var c=D.createElement({X:"div",eT:["branding-context-container-outer"]});c.appendChild(M);g.Ks(c,"right",O.image_width+"px");g.b3(D.JU(),c);D.j=new g.kF(function(){Anc(D,M,c)},500);
g.F(D,D.j);D.context.D.listen(D.JU(),"mouseover",function(){GsR(D,M,c,C,O.image_height)});
D.context.D.listen(D.JU(),"mouseout",function(){D.j.start()})}},GsR=function(D,O,h,V,k){D.j.stop();
if(!D.W){var C=g.Wt(O);D.D||(O.style.width=g.GO(C.width,!0),h.style.width=g.GO(C.width,!0));g.Ks(V,"top",C.height-Math.max(Math.min(C.height,k)/2+10,20)+"px");g.Ks(V,"right","1px");D.W=!0;g.TO(O,!0);D.J=new g.kF(function(){g.qZ(this.JU(),"iv-branding-active")},0,D);
D.J.start()}},Anc=function(D,O,h){g.Hk(D.JU(),"iv-branding-active");
D.Z=new g.kF(function(){g.TO(O,!1);D.D||(h.style.width=g.GO(0,!0))},250);
D.Z.start();D.W=!1},v2L=function(D,O,h,V,k,C,M){this.D=D;
this.j=O;this.D8=h;this.videoData=V;this.logger=k;this.C=C;this.K=M},QUJ=function(D,O,h){C$.call(this,D,O,h);
var V=this;this.T=this.isCollapsed=this.U=!1;this.Z=5E3;this.K=this.j=this.D=this.W=null;this.L=this.createElement({X:"div",eT:["iv-promo-contents"]});this.J=new g.kF(function(){V.D.setAttribute("aria-hidden","true");g.TO(V.j,!1);g.TO(V.K,!0)},700,this);
g.F(this,this.J)},sUv=function(D){var O=D.annotation.data;
if(D.annotation.style==="cta")var h=6;else if(D.annotation.style==="video"||D.annotation.style==="playlist")h=7;D.Z=O.collapsedelay_ms||D.Z;var V=["iv-promo","iv-promo-inactive"];D.JU().setAttribute("aria-hidden","true");D.JU().setAttribute("aria-label","Promotion");D.JU().tabIndex=0;var k=D.annotation.g0(),C=O.image_url;if(C){var M=D.createElement({X:"div",eT:["iv-promo-img","iv-click-target"]});C=D.createElement({X:"img",B:{src:C,"aria-hidden":"true"}});M.appendChild(C);O.video_duration&&!O.is_live?
(C=D.createElement({X:"span",Y:"iv-promo-video-duration",W3:O.video_duration}),M.appendChild(C)):O.playlist_length&&(C=D.createElement({X:"span",Y:"iv-promo-playlist-length",W3:O.playlist_length.toString()}),M.appendChild(C));k&&l7(D,M,k,D.annotation.id,O.session_data,void 0,h)}k?(C=D.createElement({X:"a",Y:"iv-promo-txt"}),g.FF(C,pM(k)),D.D=C):D.D=D.createElement({X:"div",Y:"iv-promo-txt"});switch(D.annotation.style){case "cta":case "website":var c=D.createElement({X:"p",N:[{X:"strong",W3:O.text_line_1}]});
var S=D.createElement({X:"p",N:[{X:"span",Y:"iv-promo-link",W3:O.text_line_2}]});if(C=O.text_line_3){V.push("iv-promo-website-card-cta-redesign");var Y=D.createElement({X:"button",eT:["iv-promo-round-expand-icon","ytp-button"]});C=D.createElement({X:"button",eT:["iv-button","iv-promo-button"],N:[{X:"span",Y:"iv-button-content",W3:C}]});var J=D.createElement({X:"div",Y:"iv-promo-button-container"});J.appendChild(C);k&&l7(D,D.JU(),k,D.annotation.id,O.session_data,void 0,h)}g.qZ(D.D,"iv-click-target");
k&&l7(D,D.D,k,D.annotation.id,O.session_data,void 0,h);break;case "playlist":case "video":c=D.createElement({X:"p",N:[{X:"span",W3:O.text_line_1}]}),S=D.createElement({X:"p",N:[{X:"strong",W3:O.text_line_2}]}),O.is_live&&(c=S,S=D.createElement({X:"span",eT:["yt-badge","iv-promo-badge-live"],W3:"LIVE NOW"})),g.qZ(D.D,"iv-click-target"),k&&l7(D,D.D,k,D.annotation.id,O.session_data,void 0,h),V.push("iv-promo-video")}c&&D.D.appendChild(c);S&&D.D.appendChild(S);D.L.appendChild(D.D);J&&D.L.appendChild(J);
h=D.createElement({X:"div",Y:"iv-promo-actions"});D.K=D.createElement({X:"button",eT:["iv-promo-expand","ytp-button"]});D.K.title="Expand";D.context.D.listen(D.K,"click",function(q){wFJ(D,5E3,q)});
h.appendChild(D.K);g.TO(D.K,!1);D.context.D.listen(D.JU(),"mouseover",D.OX,D);D.context.D.listen(D.JU(),"mouseout",D.Aa,D);D.context.D.listen(D.JU(),"touchend",function(q){wFJ(D,5E3,q)});
D.j=D.createElement({X:"button",eT:["iv-promo-close","ytp-button"]});D.j.title="Close";D.context.D.listen(D.j,"click",D.annotation.style==="cta"&&O.text_line_3?D.pN:D.VM,D);h.appendChild(D.j);g.uY(D.JU(),V);M&&(g.b3(D.JU(),M),Y&&M.appendChild(Y));g.b3(D.JU(),D.L);g.b3(D.JU(),h)},wFJ=function(D,O,h){h.stopPropagation();
Wem(D);TkS(D,O);D.D.focus()},dlJ=function(D){D.isCollapsed||D.T||D.W||(g.qZ(D.JU(),"iv-promo-collapsed"),D.isCollapsed=!0,D.J.start())},Wem=function(D){D.J.stop();
D.isCollapsed&&(g.my(D.JU(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),D.isCollapsed=!1,D.D&&D.D.removeAttribute("aria-hidden"),g.TO(D.K,!1),g.TO(D.j,!0))},TkS=function(D,O){D.W||(D.W=g.vg(function(){zPR(this);
dlJ(this)},O,D))},zPR=function(D){D.W&&(g.zR.clearTimeout(D.W),D.W=null)},n2S=function(D){this.C=D},xkR=function(D,O,h){O&&(h?bs(D,O.map(function(V){return g.ij(V,h)})):bs(D,O))},bs=function(D,O,h,V){var k=1,C=void 0,M=-1;
if(h){var c=!1;C=function(){k--;k||c||(clearTimeout(M),c=!0,h())};
M=setTimeout(function(){c=!0;h()},1E3)}O=g.P(O||[]);
for(var S=O.next();!S.done;S=O.next())S=S.value,k++,g.IB(S,C);V&&(k++,V!==0&&D.C.sendVideoStatsEngageEvent(V,C))},Fe_=function(D){g.dX.call(this,D);
var O=this;this.Ew=this.T=!1;this.loadNumber=0;this.Z={};this.logger=new n2S(this.player);this.W=new g.yp(this);this.J=this.L=null;this.events=new g.yp(this);this.zF=this.U=this.D=null;this.jT=[];g.F(this,this.W);this.W.G(this.player,"onVideoAreaChange",function(){O.publish("onVideoAreaChange")});
this.W.G(this.player,"onHideControls",function(){O.publish("onHideControls")});
this.W.G(this.player,"onShowControls",function(){O.publish("onShowControls")});
this.W.G(this.player,"resize",function(V){O.publish("resize",V)});
this.W.G(this.player,"presentingplayerstatechange",function(V){O.publish("presentingplayerstatechange",V)});
this.subscribe("presentingplayerstatechange",this.vV,this);this.subscribe("resize",this.mw,this);this.player.V().ST.subscribe("vast_info_card_add",this.BG,this);g.F(this,this.events);this.lS=this.createElement({X:"div",Y:"video-custom-annotations"});this.K=new g.N({X:"div",eT:["ytp-player-content","ytp-iv-player-content"]});g.F(this,this.K);g.BR(this.player,this.K.element,4);this.K.hide();this.j=new g.N({X:"div",eT:["ytp-iv-video-content"]});g.F(this,this.j);D=this.createElement({X:"div",Y:"video-annotations"});
D.appendChild(this.lS);this.j.element.appendChild(D);this.Bz()&&this.load();var h=this.createElement({X:"style"});(g.ll("HEAD")[0]||document.body).appendChild(h);this.addOnDisposeCallback(function(){g.Ye(h)});
if(D=h.sheet)D.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),D.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),D.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),D.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),D.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),D.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),D.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),D.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),D.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),D.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},ynU=function(D){D=D.createElement({X:"div",
eT:["annotation","annotation-type-custom"]});g.TO(D,!1);return D},ii_=function(D,O){O=!O.isCued()&&!g.l(O,1024);
D.K.Dn(O);D.j.Dn(O)},rnS=function(D,O,h){D.T=!0;
D.J=g.wt(O,h)},pFx=function(D,O){for(var h={},V=g.P(O.attributes),k=V.next();!k.done;k=V.next())k=k.value,h[k.name]=k.nodeValue;
for(V=0;V<O.childNodes.length;V++)if(k=O.childNodes[V],g.pT(k)&&k.nodeType==1){if(h[k.tagName])var C=h[k.tagName];else if(k.tagName==="data"){k.childNodes.length>0&&(C=k.childNodes[0].nodeValue,h[k.tagName]=typeof C==="string"?C.trim():C);continue}else C=[],h[k.tagName]=C;k&&k.tagName==="TEXT"?k.childNodes.length===1&&k.childNodes[0].nodeType===3?C.push(k.childNodes[0].nodeValue):C.push(""):k&&C.push(pFx(D,k))}return h},XFR=function(D){var O=D.player.getVideoData();
if(O.Vi){var h=D.player.V().ST.get(O.videoId);if(h){var V={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(k,C,M){k=D.loadNumber;C=O.videoId;D.loaded&&D.loadNumber===k&&D.player.getVideoData().videoId===C&&(M=g.a2(M)&&M.responseXML?M.responseXML:null)&&Nkv(D,M)}};
g.cs()&&(V.onFinish=o2c(D,V.onFinish));V.postParams={ic_only:"1"};Zi_(V,h);D.T=!0;g.wt(O.Vi,V)}}},Zi_=function(D,O){D.method="POST";
D.postParams=D.postParams||{};O.rY&&(D.postParams.ic_coll=O.rY);O.LX&&(D.postParams.ic_xml=O.LX);O.bR&&(D.postParams.ic_track=O.bR)},BkS=function(D){var O=new g.N({X:"div"});
g.TO(O.element,!1);var h=new otR(D.player,O.element,cy(D));g.F(h,O);O.CF(D.K.element);h.jY();return h},xl0=function(D,O){var h,V;
if(O=(h=O.getWatchNextResponse())==null?void 0:(V=h.cards)==null?void 0:V.cardCollectionRenderer)D.Ew=!0,lL8(D,O),O.headerText&&D.zF&&(h=g.fl(O.headerText),D.zF.setAttribute("title",h))},cy=function(D){if(!D.U){var O=new qJC(D);
g.F(D,O);var h=new g.T$(D);g.F(D,h);D.U=new v2L(O,h,D.player.V(),D.player.getVideoData(),D.logger,D.player,D.ih)}return D.U},Nkv=function(D,O){var h=!1,V=O.getElementsByTagName("annotations");
if(V&&!(V.length<1)&&(V=V[0].getAttribute("itct"))){var k=g.w_();if(k){var C=g.QK();C&&g.Cc(g.I0)(void 0,k,C,[g.th(V)])}}O=O.getElementsByTagName("annotation");for(V=0;V<O.length;V++){C=pFx(D,O[V]);k=null;try{if(C){var M=C.id,c=/.+/;var S=typeof M==="string"&&c!=null&&M!=null&&M.match(c)?M:"";var Y=rg(C.type,$lc),J=rg(C.style,IL9),q=G88(C.data),u=q.length!==0?JSON.parse(q):{};var H=C.action;C=WBc;if(H==null)var m=null;else if(g.r2(H)){c=[];for(var R=g.P(H),f=R.next();!f.done;f=R.next()){var E=C(f.value);
E&&c.push(E)}m=c}else{var A=C(H);m=A?[A]:[]}k=S&&Y?new TQ0(S,Y,J,m,u):null}else k=null}catch(hd){}if(k)if(k.type==="branding"||k.type==="promotion"){C=D;c=k;var v=ynU(C),W=null;switch(c.type){case "branding":if(C.player.V().UW)break;C.K.element.appendChild(v);W=new ME(v,cy(C),c);break;case "promotion":g.BR(C.player,v,4),W=new QUJ(v,cy(C),c)}W&&W.jY();if(C=W)g.F(D,C),D.Z[k.id]=C}else if(k.type==="card"||k.type==="drawer"){D.D||(D.D=BkS(D),g.F(D,D.D));if(k.type==="card"){v=D.D;var z=(h=k)&&h.data&&
h.data.card_type;k=h.data;if(z)switch(C=k.tracking||{},C={xp:C.impression,click:C.click,close:C.close,Md:C.teaser_impression,gi:C.teaser_click},c=k.tracking_params||{},W=null,z){case "collaborator":h={id:h.id,timestamp:k.timestamp||0,type:k.card_type,teaserText:k.teaser_text,teaserDurationMs:k.teaser_duration_ms,startMs:k.start_ms,autoOpen:k.auto_open||!1,sessionData:k.session_data||{},sponsored:k.sponsored||!1,CO:C,ON:c.card?g.th(c.card):null,Qs:c.teaser?g.th(c.teaser):null,Pa:c.icon?g.th(c.icon):
null,channelId:k.channel_id,customMessage:k.custom_message?k.custom_message:null,profileImageUrl:k.image_url,title:k.title,metaInfo:k.meta_info,url:Nb({pause_on_navigation:k.pause_on_navigation,target:k.target||"new",value:k.url}),onClickCommand:null};D5(v,h);break;case "playlist":h={id:h.id,timestamp:k.timestamp||0,type:k.card_type,teaserText:k.teaser_text,teaserDurationMs:k.teaser_duration_ms,startMs:k.start_ms,autoOpen:k.auto_open||!1,sessionData:k.session_data||{},sponsored:k.sponsored||!1,CO:C,
ON:c.card?g.th(c.card):null,Qs:c.teaser?g.th(c.teaser):null,Pa:c.icon?g.th(c.icon):null,sI:k.image_url,playlistVideoCount:k.playlist_video_count,customMessage:k.custom_message?k.custom_message:null,title:k.title,metaInfo:k.meta_info,url:Nb({pause_on_navigation:k.pause_on_navigation,target:k.target||"new",value:k.url}),onClickCommand:null};D5(v,h);break;case "productListing":k.signin_url&&(W=Nb({target:"current",value:k.signin_url}));z=[];for(var X=k.offers||[],Z=0;Z<X.length;Z++)z.push(new ibR(g.k$(X[Z].merchant),
g.k$(X[Z].price)));h={id:h.id,timestamp:k.timestamp||0,type:k.card_type,teaserText:k.teaser_text,teaserDurationMs:k.teaser_duration_ms,startMs:k.start_ms,autoOpen:k.auto_open||!1,sessionData:k.session_data||{},sponsored:k.sponsored||!1,CO:C,ON:c.card?g.th(c.card):null,Qs:c.teaser?g.th(c.teaser):null,Pa:c.icon?g.th(c.icon):null,imageUrl:k.image_url,displayDomain:k.display_domain?k.display_domain:null,showLinkIcon:!!k.show_link_icon,hw:k.button_icon_url?k.button_icon_url:null,title:k.title,customMessage:k.custom_message?
k.custom_message:null,url:Nb({pause_on_navigation:k.pause_on_navigation,target:k.target||"new",value:k.url}),DD3:W,Uw2:k.signin_title?k.signin_title:void 0,mwa:k.signin_message?k.signin_message:void 0,offers:z,onClickCommand:null};D5(v,h);break;case "simple":h={id:h.id,timestamp:k.timestamp||0,type:k.card_type,teaserText:k.teaser_text,teaserDurationMs:k.teaser_duration_ms,startMs:k.start_ms,autoOpen:k.auto_open||!1,sessionData:k.session_data||{},sponsored:k.sponsored||!1,CO:C,ON:c.card?g.th(c.card):
null,Qs:c.teaser?g.th(c.teaser):null,Pa:c.icon?g.th(c.icon):null,imageUrl:k.image_url,displayDomain:k.display_domain?k.display_domain:null,showLinkIcon:!!k.show_link_icon,hw:k.button_icon_url?k.button_icon_url:null,title:k.title,customMessage:k.custom_message?k.custom_message:null,url:Nb({pause_on_navigation:k.pause_on_navigation,target:k.target||"new",value:k.url}),onClickCommand:null};D5(v,h);break;case "video":h={id:h.id,timestamp:k.timestamp||0,type:k.card_type,teaserText:k.teaser_text,teaserDurationMs:k.teaser_duration_ms,
startMs:k.start_ms,autoOpen:k.auto_open||!1,sessionData:k.session_data||{},sponsored:k.sponsored||!1,CO:C,ON:c.card?g.th(c.card):null,Qs:c.teaser?g.th(c.teaser):null,Pa:c.icon?g.th(c.icon):null,sI:k.image_url,videoDuration:k.video_duration||null,customMessage:k.custom_message?k.custom_message:null,title:k.title,metaInfo:k.meta_info,isLiveNow:!!k.is_live_now,url:Nb({pause_on_navigation:k.pause_on_navigation,target:k.target||"new",value:k.url}),onClickCommand:null},D5(v,h)}}else Zb8(D.D,k);h=!0}}h&&
(Uw(D.player),D.mw())},lL8=function(D,O){var h=!1;
D.D||(D.D=BkS(D),g.F(D,D.D));for(var V=g.P(O.cards||[]),k=V.next();!k.done;k=V.next())k=k.value,k.cardRenderer&&(X8C(D.D,k.cardRenderer),h=!0);if(h){var C;(C=D.player.getVideoData())!=null&&g.xG(C)||(h=D.D,V=O.headerText?g.fl(O.headerText):"",g.qf(h.yy,V),h.T&&h.T.setAttribute("title",V),h.context.videoData.eventId&&(h.eventId=h.context.videoData.eventId),h.X1=O.trackingParams?g.th(O.trackingParams):null,h.L=O.closeButton.infoCardIconRenderer.trackingParams?g.th(O.closeButton.infoCardIconRenderer.trackingParams):
null,h.Pa=O.icon.infoCardIconRenderer.trackingParams?g.th(O.icon.infoCardIconRenderer.trackingParams):null,D.mw());Uw(D.player)}},DRJ=function(D,O,h,V,k){if(!D.player.V().UW){var C=[];
O.navigationEndpoint&&g.y(O.navigationEndpoint,g.jG)&&g.y(O.navigationEndpoint,g.jG).browseId&&C.push(new QjJ("openUrl","click",new tE_("/channel/"+g.y(O.navigationEndpoint,g.jG).browseId,"new",!0,!0)));var M=O.watermark.thumbnails[0];V={channel_name:O.channelName,end_ms:O.endTimeMs,image_height:M.height,image_type:1,image_url:M.url,image_width:M.width,is_mobile:!1,session_data:{annotation_id:h,ei:k,feature:"iv",itct:O.trackingParams,src_vid:V},start_ms:O.startTimeMs};if(O.subscribeButton&&g.y(O.subscribeButton,
g.Um)){V.channel_id=g.y(O.subscribeButton,g.Um).channelId;var c;O=g.y(O.subscribeButton,g.Um);M=k=null;O.subscribed?(O.subscriberCountWithUnsubscribeText&&(k=g.fl(O.subscriberCountWithUnsubscribeText)),O.subscriberCountText&&(M=g.fl(O.subscriberCountText))):(O.subscriberCountText&&(k=g.fl(O.subscriberCountText)),O.subscriberCountWithSubscribeText&&(M=g.fl(O.subscriberCountWithSubscribeText)));var S,Y=((S=g.y((c=O.signInEndpoint)==null?void 0:c.commandMetadata,g.g4))==null?void 0:S.url)||"";c={subscribeText:g.fl(O.unsubscribedButtonText),
subscribeCount:k||"",unsubscribeText:g.fl(O.subscribedButtonText),unsubscribeCount:M||"",enabled:O.enabled||!1,classic:!1,subscribed:O.subscribed||!1,feature:"iv",signInUrl:Y};V.standalone_subscribe_button_data=c}C=new TQ0(h,"branding","branding",C,V);c=ynU(D);D.K.element.appendChild(c);C=new ME(c,cy(D),C);C.jY();g.F(C,C);D.Z[h]=C}},o2c=function(D,O){return function(){var h=g.GR.apply(0,arguments);
D.Z8()||D.jT.push(g.x7.Oe(function(){O.apply(null,g.a(h))}))}},O2R=function(D){return D==="annotation-editor"||D==="live-dashboard"};
g.yD.prototype.W_=g.V_(39,function(D,O){var h=g.xq(this.Ev());h&&h.W_(D,O)});
var Gy={},tW=null;g.$w(QF,g.Ld);g.b=QF.prototype;g.b.getDuration=function(){return this.duration};
g.b.play=function(D){if(D||this.D==0)this.progress=0,this.coords=this.K;else if(this.isPlaying())return!1;vY(this);this.startTime=D=g.xw();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.W=this.startTime;this.progress||this.Vb();this.Zp("play");this.isPaused()&&this.Zp("resume");this.D=1;var O=g.Zy(this);O in Gy||(Gy[O]=this);CDU();MES(this,D);return!0};
g.b.stop=function(D){vY(this);this.D=0;D&&(this.progress=1);bbJ(this,this.progress);this.onStop();this.J$()};
g.b.pause=function(){this.isPlaying()&&(vY(this),this.D=-1,this.Zp("pause"))};
g.b.fF=function(){this.D==0||this.stop(!1);this.Zp("destroy");QF.E_.fF.call(this)};
g.b.destroy=function(){this.dispose()};
g.b.PL=function(){this.Zp("animate")};
g.b.Zp=function(D){this.dispatchEvent(new cFJ(D,this))};
g.$w(cFJ,g.rj);g.$w(wg,QF);wg.prototype.j=function(){};
wg.prototype.PL=function(){this.j();wg.E_.PL.call(this)};
wg.prototype.J$=function(){this.j();wg.E_.J$.call(this)};
wg.prototype.Vb=function(){this.j();wg.E_.Vb.call(this)};
g.$w(SJJ,wg);SJJ.prototype.j=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.e(qJC,g.n);g.b=qJC.prototype;g.b.listen=function(D,O,h,V){h=(0,g.Xk)(h,V||this.K);D=g.GF(D,O,h);this.D.push(D);return D};
g.b.Mb=function(D,O,h,V){h=(0,g.Xk)(h,V||this.K);D=VEC(D,O,h);this.D.push(D);return D};
g.b.Cp=function(D){g.ta(D);g.xC(this.D,D)};
g.b.removeAll=function(){g.ta(this.D);this.D.length=0};
g.b.fF=function(){this.removeAll();g.n.prototype.fF.call(this)};g.e(mk8,g.dX);g.b=mk8.prototype;g.b.load=function(){g.dX.prototype.load.call(this);if(!dg(this)){var D=g.YXd(this.player.getVideoData());D?(D=Hbv(D,eE9(this)),zy(this,D,!1)):LBR(this)}};
g.b.unload=function(){zy(this,null);this.W&&(this.W.abort(),this.W=null);g.dX.prototype.unload.call(this)};
g.b.mG=function(D,O){return dg(this)?D==="loadCustomEndscreenRenderer"?(D=Hbv(O,"new"),zy(this,D),!0):null:null};
g.b.getOptions=function(){return dg(this)?["loadCustomEndscreenRenderer"]:[]};
g.b.PQ=function(){if(this.endscreen&&this.endscreen.elements){var D=this.player.getVideoContentRect();if(D&&D.width!==0&&D.height!==0){var O=this.player.getPlayerSize();if(O&&O.width!==0&&O.height!==0){var h=D.width/D.height;var V=0;for(var k=-1,C=0;C<hzc.length;C++){var M=Math.abs(O.width-hzc[C]);if(k===-1||V>=M)k=C,V=M}V=Vrv[k];this.j&&g.Ks(this.j.element,"outline-width",Math.max(O.width,O.height)+"px");for(O=0;O<this.endscreen.elements.length;++O)if(C=this.endscreen.elements[O].id,k=this.K[C],
M=this.Z[C],k&&M){var c=M.width*h/M.aspectRatio,S=Math.round(M.width*D.width);C=Math.round(c*D.height);var Y=D.left+Math.round(M.left*D.width),J=D.top+Math.round(M.top*D.height);g.sy(k.element,S,C);g.tu(k.element,Y,J);g.my(k.element,k_x);S>256||C>256?g.qZ(k.element,"ytp-ce-large-round"):S>96||C>96?g.qZ(k.element,"ytp-ce-medium-round"):g.qZ(k.element,"ytp-ce-small-round");g.my(k.element,Clm);S=M.left+M.width/2;M=M.top+c/2;g.qZ(k.element,S<=.5&&M<=.5?"ytp-ce-top-left-quad":S>.5&&M<=.5?"ytp-ce-top-right-quad":
S<=.5&&M>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.my(k.element,Vrv);g.qZ(k.element,V);(k=g.$$(document,"div","ytp-ce-expanding-overlay-body",k.element)[0])&&g.Ks(k,"height",C+"px")}}}}};
g.b.onCueRangeEnter=function(D){if(this.endscreen)if(D.getId()==="ytp-ce-in-endscreen")i7(this,this.endscreen.impressionUrls),(D=g.w_())&&this.endscreen.visualElement&&g.cG(D,this.endscreen.visualElement),this.D&&(g.qZ(this.D,"ytp-ce-element-show"),this.D.removeAttribute("aria-hidden"),this.player.JE()?g.qZ(this.D,"ytp-ce-hide-button-lower"):g.Hk(this.D,"ytp-ce-hide-button-lower"));else{D=D.getId().substring(15);var O=this.K[D],h=this.Z[D];g.qZ(O.element,"ytp-ce-element-show");O.element.removeAttribute("aria-hidden");
O=this.player.getRootNode();g.qZ(O,"ytp-ce-shown");i7(this,h.impressionUrls);(O=g.w_())&&g.cG(O,h.visualElement);this.player.V().L&&this.player.F1("endscreenelementshown",D)}};
g.b.onCueRangeExit=function(D){if(D.getId()==="ytp-ce-in-endscreen")this.D&&(g.Hk(this.D,"ytp-ce-element-show"),this.D.setAttribute("aria-hidden","true"));else{D=D.getId().substring(15);var O=this.K[D];g.Hk(O.element,"ytp-ce-element-show");O.element.setAttribute("aria-hidden","true");O=this.player.getRootNode();g.Hk(O,"ytp-ce-shown");this.player.V().L&&this.player.F1("endscreenelementhidden",D)}};
g.b.B0i=function(D){var O=this;D.target===window&&(new g.kF(function(){for(var h=g.P(Object.values(O.K)),V=h.next();!V.done;V=h.next())g.my(V.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.b.Dn=function(D){for(var O=g.P(Object.values(this.K)),h=O.next();!h.done;h=O.next())h=h.value,D?h.element.setAttribute("hidden",""):h.element.removeAttribute("hidden")};
g.b.Z2w=function(D){this.D&&this.player.getRootNode().removeChild(this.D);D&&(g.qZ(D,"ytp-ce-hide-button-container"),this.D=D,g.BR(this.player,this.D,4))};
var hzc=[346,426,470,506,570,640,853,1280,1920],Vrv="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Clm=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],k_x=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var vtL={ZO8:"current",K_7:"new"};var w8L={CLOSE:"close",fox:"openUrl",SUBSCRIBE:"subscribe"},sjv={jeS:"click",CLOSE:"close",yE7:"hidden",oq8:"rollOut",F_T:"rollOver",jA5:"shown"};TQ0.prototype.g0=function(){var D=dkR(this,function(O){return O.type==="openUrl"&&O.url!=null});
return D?D.url:null};
var IL9={XNx:"anchored",A3:"branding",CHANNEL:"channel",wp8:"cta",g_1:"highlightText",cfW:"label",PLAYLIST:"playlist",POPUP:"popup",zIE:"speech",SUBSCRIBE:"subscribe",MG5:"title",VIDEO:"video",Icx:"website"},$lc={A3:"branding",oy1:"card",bOW:"drawer",sdx:"highlight",aka:"marker",hUE:"promotion",TEXT:"text",GcW:"widget"};g.e(BY,g.n);g.b=BY.prototype;g.b.addCueRange=function(D,O,h,V,k){D=new g.S4(D,O,{id:h,namespace:"annotations_module"});V&&this.Vi.set(D,V);k&&this.Ax.set(D,k);this.context.C.nW([D],1)};
g.b.jY=function(){this.context.K.subscribe("resize",this.AP,this)};
g.b.JU=function(){return this.element};
g.b.fq=function(D,O,h,V,k,C){if(this.m5)return!1;C&&(C.stopPropagation(),C.preventDefault());this.navigate(D,h,V,k);return!1};
g.b.show=function(){};
g.b.hide=function(){};
g.b.destroy=function(){g.Ye(this.JU())};
g.b.AP=function(){};
g.b.navigate=function(D,O,h,V){var k=this,C=pM(D);if(C){var M=p8S(C,D.target),c=function(){D.D&&k.context.C.pauseVideo();var S=k.context.videoData.Q$||!1,Y=g.JO(C||"");S&&Y&&(Y.v||Y.list)?k.context.C.d5(Y.v,O,Y.list,!1):g.lH(C||"",M==="current"?"_top":void 0,O)};
M==="new"&&(c(),c=null);bs(this.context.logger,h,c,V);rFR(C)||(h=g.w_(),V=O.itct,h&&V&&g.JA(h,g.th(V)))}};
g.b.fF=function(){this.Vi.clear();this.Ax.clear();g.n.prototype.fF.call(this)};
g.b.createElement=function(D){D=new g.N(D);g.F(this,D);return D.element};g.e(otR,BY);g.b=otR.prototype;g.b.PR=function(){this.jT&&D5(this,this.jT)};
g.b.isAvailable=function(){var D;if(D=!!this.cards.length)(D=this.C.getRootNode())?(D=g.Wt(D),D=173<D.width&&173<D.height):D=!1;return D};
g.b.AP=function(){var D=this.isAvailable();g.TO(this.JU(),D);g.eX(this.context.C.getRootNode(),g.pI.IV_DRAWER_ENABLED,D);Uw(this.C)};
g.b.destroy=function(){this.C.W_(!1);try{this.C.getRootNode().removeChild(this.W)}catch(D){}g.P9(this.Ew);g.d6(this.LF);this.G2&&this.G2.dispose();this.J&&this.J.dispose();BY.prototype.destroy.call(this)};
g.b.Mf=function(){var D=this;this.context.D.listen(g.Io("iv-drawer-close-button",this.W),"click",this.gR,this);this.context.D.listen(this.K,"touchend",function(){D.qE.start()});
this.context.D.listen(this.K,"scroll",this.WE,this);this.context.K.subscribe("onHideControls",function(){D.ST=!0});
this.context.K.subscribe("onShowControls",function(){D.ST=!1});
this.context.K.subscribe("onVideoAreaChange",function(){D.ST=g.JX(D.C.getRootNode(),"ytp-autohide")});
this.Ew.push(g.LY("iv-button-shown",this.PS7,this));this.Ew.push(g.LY("iv-button-hidden",this.OFW,this));IZe(this)};
g.b.findLastIndex=function(D){if(this.cards.length===0)return 0;var O=g.X8(this.cards,function(h){return D.pG.startMs>h.pG.startMs||D.pG.startMs===h.pG.startMs&&D.pG.timestamp>=h.pG.timestamp?!0:!1});
return O===-1?0:O+1};
g.b.gR=function(){if(this.j){bs(this.context.logger,kQ(this).CO.close);var D=g.w_();D&&this.L&&g.JA(D,this.L);Iq(this)}};
g.b.WE=function(){g.eX(this.W,"iv-drawer-scrolled",this.K.scrollTop>0)};
g.b.PS7=function(){var D=g.w_(),O=kQ(this);O=O?O.Pa:this.Pa;D&&O&&g.Sg(D,[O])};
g.b.OFW=function(){var D=g.w_(),O=kQ(this);O=O?O.Pa:this.Pa;D&&O&&g.YR(D,[O])};
g.b.zT=function(){var D=kQ(this);bs(this.context.logger,D.CO.Md);var O=g.w_();if(O&&D)if(this.C.S("web_infocards_teaser_show_logging_fix")){var h=[];D.Qs&&h.push(D.Qs);D.Pa&&h.push(D.Pa);h.length>0&&g.Sg(O,h)}else g.Sg(O,[D.Qs,D.Pa])};
g.b.o71=function(){var D=g.w_(),O=kQ(this);D&&O&&g.YR(D,[O.Qs])};
g.b.q$=function(D){var O=kQ(this),h=g.w_();this.D?D?(D=this.context.logger,bs(D,O.CO.gi),D.C.sendVideoStatsEngageEvent(4,void 0),h&&O.Qs&&g.JA(h,O.Qs)):(D=this.context.logger,bs(D,O.CO.gi),D.C.sendVideoStatsEngageEvent(4,void 0),h&&O.Pa&&g.JA(h,O.Pa)):(D=this.context.logger,bs(D,O.CO.gi),D.C.sendVideoStatsEngageEvent(4,void 0),h&&this.Pa&&g.JA(h,this.Pa))};g.e(C$,BY);C$.prototype.jY=function(){BY.prototype.jY.call(this);jUR(this)};
C$.prototype.show=function(){BY.prototype.show.call(this);var D=g.w_(),O=this.annotation.data;D&&O&&(O=O.session_data)&&g.Sg(D,[g.th(O.itct)])};
C$.prototype.hide=function(){BY.prototype.hide.call(this);var D=g.w_(),O=this.annotation.data;D&&O&&(O=O.session_data)&&g.YR(D,[g.th(O.itct)])};g.e(ME,C$);
ME.prototype.show=function(){if(!this.isActive){C$.prototype.show.call(this);if(!this.L){g.qZ(this.JU(),"iv-branding");var D=this.annotation.data;this.K=this.createElement({X:"img",eT:["branding-img","iv-click-target"],B:{"aria-label":"Channel watermark",src:D.image_url,width:D.image_width,height:D.image_height}});g.TO(this.K,!1);var O=this.createElement({X:"button",eT:["branding-img-container","ytp-button"]});O.appendChild(this.K);this.JU().appendChild(O);var h=this.annotation.g0();h&&l7(this,O,
h,this.annotation.id,D.session_data);this.context.C.S("disable_branding_context")||tD0(this,D);this.L=!0}g.TO(this.JU(),!0);this.isActive=!0;if(this.K){try{UlL(this,this.K)}catch(V){}g.qZ(this.context.C.getRootNode(),"ytp-branding-shown");this.context.C.getRootNode().style.setProperty("--branding-image-width",this.K.getAttribute("width")+"px")}}};
ME.prototype.hide=function(){this.isActive&&(C$.prototype.hide.call(this),g.TO(this.JU(),!1),this.isActive=!1,g.Hk(this.context.C.getRootNode(),"ytp-branding-shown"))};
ME.prototype.destroy=function(){this.D&&(this.D.dispose(),this.D=null);g.Hk(this.context.C.getRootNode(),"ytp-branding-shown");C$.prototype.destroy.call(this)};g.e(QUJ,C$);g.b=QUJ.prototype;g.b.show=function(){this.isActive||(C$.prototype.show.call(this),this.U||(sUv(this),this.U=!0),g.TO(this.JU(),!0),g.vg(function(){g.Hk(this.JU(),"iv-promo-inactive")},100,this),this.JU().removeAttribute("aria-hidden"),this.isActive=!0,zPR(this),Wem(this),TkS(this,this.Z))};
g.b.hide=function(){this.isActive&&(g.qZ(this.JU(),"iv-promo-inactive"),this.isActive=!1,this.JU().setAttribute("aria-hidden","true"))};
g.b.fq=function(D,O,h,V,k,C){return this.isCollapsed?!1:C$.prototype.fq.call(this,D,O,h,V,k,C)};
g.b.OX=function(D){this.T=!0;wFJ(this,500,D)};
g.b.Aa=function(){this.T=!1;dlJ(this)};
g.b.VM=function(D){D.stopPropagation();this.hide()};
g.b.pN=function(D){D.stopPropagation();zPR(this);this.isCollapsed=!0;g.qZ(this.JU(),"iv-promo-collapsed-no-delay");this.J.start()};
g.b.destroy=function(){this.J.dispose();C$.prototype.destroy.call(this)};g.e(Fe_,g.dX);g.b=Fe_.prototype;g.b.mG=function(D,O){if(!O2R(this.player.V().playerStyle))return null;switch(D){case "loadCustomAnnotationsXml":return(D=g.xl(O))&&Nkv(this,D),!0;case "removeCustomAnnotationById":return O&&this.D&&(lZx(this.D,O),Uw(this.player)),!0}return null};
g.b.getOptions=function(){return O2R(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.b.Bz=function(){var D=this.player.V(),O=this.player.getVideoData(),h=D.annotationsLoadPolicy||O.annotationsLoadPolicy;return g.eU(O)||this.player.isMutedByEmbedsMutedAutoplay()?!1:h===1&&!O.a8||D.ST.get(O.videoId)||g.O5(O)||g.hy(O)?!0:!1};
g.b.mw=function(){if(this.j){var D=this.player.B3().getVideoContentRect(!0);g.sy(this.j.element,D.width,D.height);g.tu(this.j.element,D.left,D.top)}if(this.D){var O=this.player.sY();D=this.D;O=O.width;g.eX(D.W,"iv-drawer-small",O<=426);g.eX(D.W,"iv-drawer-big",O>=1280)}};
g.b.vV=function(D){ii_(this,D.state);g.l(D.state,2)&&(this.JE()&&this.i4()&&this.player.getPresentingPlayerType()!==2&&this.uu(!1),this.W_(!1))};
g.b.load=function(){function D(M){var c=O.loadNumber;O.J=null;O.loaded&&O.loadNumber===c&&O.player.getVideoData().videoId===V&&(M=g.a2(M)&&M.responseXML?M.responseXML:null)&&(Nkv(O,M),g.qZ(O.player.getRootNode(),"iv-module-loaded"))}
var O=this;g.dX.prototype.load.call(this);ii_(this,this.player.getPlayerStateObject());this.loadNumber++;var h=this.player.getVideoData(),V=h.videoId;g.cs()&&(D=o2c(this,D));var k={format:"XML",onFinish:D,onError:function(){O.J=null},
urlParams:{}};h.isPharma&&(k.urlParams.pharma="1");k.method="POST";k.withCredentials=!0;var C=this.player.V().ST.get(V);C&&Zi_(k,C);C=C&&(C.LX||C.rY);if(!h.i6||C)h.Vi?rnS(this,h.Vi,k):(this.L=function(){if(!O.T)O.onVideoDataChange(k);var M=O.player.getVideoData();(M==null?0:g.xG(M))&&!O.Ew&&xl0(O,M)},this.player.addEventListener("videodatachange",this.L));
g.BR(this.player,this.j.element,4);this.mw();(C=g.O5(h))&&lL8(this,C);(C=g.hy(h))&&C.featuredChannel&&DRJ(this,C.featuredChannel,C.annotationId||"branding",h.videoId||null,h.eventId||null);this.zF=g.Io("ytp-cards-button",this.player.getRootNode());g.xG(h)&&xl0(this,h)};
g.b.onVideoDataChange=function(D){var O=this.player.getVideoData();O.Vi&&rnS(this,O.Vi,D)};
g.b.unload=function(){this.player.Y8("annotations_module");for(var D=g.P(Object.keys(this.Z)),O=D.next();!O.done;O=D.next())this.Z[O.value].destroy();this.U=null;this.D&&(this.D.destroy(),this.D=null,Uw(this.player));this.T=!1;this.J&&(this.J.abort(),this.J=null);this.Ew=!1;this.Z={};this.K.hide();g.dX.prototype.unload.call(this);this.j.detach();this.L&&(this.player.removeEventListener("videodatachange",this.L),this.L=null)};
g.b.BG=function(D){D===this.player.getVideoData().videoId&&(this.loaded?XFR(this):this.load())};
g.b.JE=function(){var D;return((D=this.D)==null?void 0:D.isAvailable())||this.Ew};
g.b.i4=function(){return!!this.D&&this.D.j};
g.b.uu=function(D,O,h){O=O===void 0?!1:O;this.JE();this.D&&(D?h?$r(this.D,h,O):$r(this.D,"YOUTUBE_DRAWER_AUTO_OPEN",O):Iq(this.D))};
g.b.W_=function(D,O){this.player.publish(D?"cardsteasershow":"cardsteaserhide",O)};
g.b.fF=function(){this.player.V().ST.unsubscribe("vast_info_card_add",this.BG,this);g.Hk(this.player.getRootNode(),g.pI.IV_DRAWER_OPEN);for(var D=this.jT,O=g.x7,h=0,V=D.length;h<V;h++)O.zE(D[h]);this.jT.length=0;g.dX.prototype.fF.call(this)};
g.b.createElement=function(D){D=new g.N(D);g.F(this,D);return D.element};g.TP("annotations_module",Fe_);g.TP("creatorendscreen",mk8);})(_yt_player);
