(function(g){var window=this;'use strict';var cpR=function(D,O,h){g.Q(function(V){D.K=g.wt(O,h);g.LT(V)})},SH=function(D){D.isActive()||D.start()},SOC=function(D,O){return O?D.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},YO_=function(D){return g.Z$(D)||D.S("web_enable_caption_language_preference_stickiness")},JpR=function(D,O){var h=new g.Yi;
h.languageCode=D.languageCode;h.languageName=D.languageName;h.name=D.name;h.displayName=D.displayName;h.kind=D.kind;h.isDefault=!1;h.D=D.D;h.isTranslateable=D.isTranslateable;h.vssId=D.vssId;h.url=D.url;h.translationLanguage=O;D.xtags&&(h.xtags=D.xtags);D.captionId&&(h.captionId=D.captionId);return h},qO9=function(D,O){var h,V,k;
return g.Q(function(C){if(C.D==1)return h=D+"|"+O,g.t(C,g.CL(),2);if(C.D!=3){V=C.K;if(!V)throw g.G9("gct");return g.t(C,g.Gl(V),3)}k=C.K;return C.return(k.get("captions",h))})},upC=function(D,O,h){qO9(D,O).then(function(V){V&&h(V.trackData,new g.Yi(V.metadata))})},ezS=function(D){if(!H2U.test(D))throw Error("'"+D+"' is not a valid hex color");
D.length==4&&(D=D.replace(mRU,"#$1$1$2$2$3$3"));D=D.toLowerCase();D=parseInt(D.slice(1),16);return[D>>16,D>>8&255,D&255]},LSm=function(){var D=void 0;
D=D===void 0?{}:D;var O="suggest_correction"in g.K68?g.K68.suggest_correction:"Edit caption";O=O||"";var h={},V;for(V in D){h={vY:h.vY};h.vY=V;var k=function(C){return function(){return String(D[C.vY])}}(h);
O=O.replace(new RegExp("\\$\\{"+h.vY+"\\}","gi"),k);O=O.replace(new RegExp("\\$"+h.vY,"gi"),k)}return O},Ple=function(){return g.i0("yt-player-caption-display-settings")},YQ=function(){this.segments=[]},g$v=function(D,O){var h=g.Mt(D.segments,O);
h>=0||h<0&&(-h-1)%2===1||(h=-h-1,h>0&&O-D.segments[h-1]===1&&h<D.segments.length&&D.segments[h]-O===1?(g.l_(D.segments,h),g.l_(D.segments,h-1)):h>0&&O-D.segments[h-1]===1?D.segments[h-1]=O:h<D.segments.length&&D.segments[h]-O===1?D.segments[h]=O:(g.VL(D.segments,h,0,O),g.VL(D.segments,h+1,0,O)))},RzS=function(D,O,h,V,k,C){g.n.call(this);
this.policy=D;this.player=O;this.Ew=h;this.T=V;this.J=k;this.U=C;this.W=new YQ;this.Z=-1;this.j=this.K=this.D=null;this.jT=0;this.L=new g.kF(this.dG,1E3,this);this.events=new g.yp(this);g.F(this,this.L);g.F(this,this.events);this.events.G(O,"SEEK_COMPLETE",this.Rm);this.Rm();this.dG()},ap_=function(D){return D.D&&D.D.gU?D.D.gU+D.player.Uv()<D.player.getCurrentTime():!1},fpx=function(D,O){if(D.policy.Em&&D.player.tN()){var h=g.yz(O,D.policy,{});
h.set("pot",D.player.tN());h=h.g0()}else h=g.yz(O,D.policy,{}).g0();var V={format:"RAW",withCredentials:!0};if(D.policy.ST){V.method="POST";var k=O.W;k&&Object.keys(k).length>0?V.postBody=g.SS(k,g.$J):V.postBody=(0,g.GT)([120,0])}D.J&&(V.responseType="arraybuffer");var C=++D.jT,M=(0,g.Ws)();D.j=g.dt(h,V,3,100).then(function(c){if(D.policy.mI&&C%100===1){var S=(0,g.Ws)();D.player.KF("caprsp",{rn:C,ms:S-M,kb:(c.xhr.responseText.length/1024).toFixed()})}a:{c=c.xhr;D.Z8();if(D.K){var Y=!(D.J?c.response:
c.responseText)||c.status>=400;if(S=g.EgR(c)){c=g.yz(D.K,D.policy,{});D.K.sf(c,S);fpx(D,D.K);break a}Y?D.player.KF("capfail",{status:c.status}):(D.player.pm().XJ("fcb_r"),S=D.K.ra[0].hx,D.T!=null&&D.Z!==S&&(Y=D.K.ra[0],D.J?D.T(c.response,(Y.startTime+D.player.Uv())*1E3):D.T(c.responseText,(Y.startTime+D.player.Uv())*1E3),D.Z=S))}D.K=null;D.j=null}}).QL(function(c){D.K=null;
D.j=null;var S;D.player.KF("capfail",{rn:C,status:(S=c.xhr)==null?void 0:S.status})});
D.K=O;g$v(D.W,D.K.ra[0].hx)},Jm=function(D,O){g.nu.call(this,O);
this.K=D;this.C=O;this.j=null;this.Z=!1;this.L=g.v5(this.C.V())&&!this.K.isManifestless},E$0=function(D,O){var h=[],V;
for(V in D.K.D)if(D.K.D.hasOwnProperty(V)){var k=D.K.D[V];if(g.yr(k,O||null)){var C=k.info.id,M=C,c="."+C,S="",Y="";if(k=k.info.captionTrack)C=k.languageCode,M=k.displayName,c=k.vssId,S=k.kind,Y=k.id;else{k=C;var J=g.pV0.get(k);J==null&&(J=KSm[k]||KSm[k.replace(/-/g,"_")],g.pV0.set(k,J));k=J;M=k||M}h.push(new g.Yi({id:V,languageCode:C,languageName:M,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:c,kind:S,captionId:Y}))}}return h},jox=function(D,O){return O!=null&&O in D.K.D?D.K.D[O]:null},
URJ=function(D,O,h){var V=[],k;
for(k in D.K.D)if(D.K.D.hasOwnProperty(k)){var C=D.K.D[k];if(g.yr(C,h||null)){var M=C.info.captionTrack;M&&M.languageCode===O&&V.push(C)}}return V.length?V[0]:null},qE=function(D,O,h,V,k,C,M,c,S,Y){var J=Y.isInline()&&!0,q={};
Object.assign(q,O);Object.assign(q,D.params);Object.assign(q,h);var u={};Object.assign(u,O.IK);D.params.IK&&Object.assign(u,D.params.IK);Object.assign(u,h.IK);J&&(q.windowOpacity=.6,u.backgroundOpacity=0);q.IK=u;var H=q.T3===1,m=[{X:"span",Y:"captions-text",B:{style:"word-wrap: normal; display: block;"}}],R,f,E;(c=c.P3("caption_edit_on_hover")&&((R=Y.getVideoData().getPlayerResponse())==null?void 0:(f=R.captions)==null?void 0:(E=f.playerCaptionsTracklistRenderer)==null?void 0:E.openTranscriptCommand))&&
m.unshift({X:"button",Y:"caption-edit",B:{tabindex:"0","aria-label":LSm()},N:[{X:"svg",B:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},N:[{X:"path",B:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.N.call(this,{X:"div",Y:"caption-window",B:{id:"caption-window-"+D.id,dir:H?"rtl":"ltr",tabindex:"0",lang:q.lang},N:m});var A=
this;this.L=[];this.X1=!1;this.K=D;this.ST=this.ME=null;this.playerWidth=C;this.playerHeight=M;this.T=null;this.maxWidth=C*.96;this.maxHeight=M*.96;this.D=q;this.Qy=h;this.jT=O;this.W=this.z2("captions-text");this.L1=this.W.style.getPropertyValue("box-decoration-break")!==""||this.W.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.G2=Apc(V,k,C,M);this.F2=S;c&&(this.J=this.z2("caption-edit"),this.G(this.J,"click",function(){A.F2()}));
this.type=0;this.Ax=this.G2*G_U(u);this.f1=J;D=new g.ST(this.element,!0);g.F(this,D);D.subscribe("dragstart",this.CP,this);D.subscribe("dragmove",this.XA,this);D.subscribe("dragend",this.cV,this);this.oW=this.T2=this.Uw=this.m5=0;D="";this.D.windowOpacity&&(D=ezS(this.D.windowColor),D="rgba("+D[0]+","+D[1]+","+D[2]+","+this.D.windowOpacity+")");O={"background-color":D,display:this.D.isVisible===!1?"none":"","text-align":trL[this.D.textAlign]};this.L1&&(O["border-radius"]=D?this.Ax/8+"px":"");(this.j=
this.K.params.T3===2||this.K.params.T3===3)&&v$8(this,this.element);g.Ks(this.element,O);if(J){var v;(v=this.element.parentElement)==null||v.style.setProperty("--caption-window-color",D)}switch(this.D.zo){case 0:case 1:case 2:g.qZ(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.qZ(this.element,"ytp-caption-window-bottom")}},v$8=function(D,O){var h="vertical-rl";
D.D.tJ===1&&(h="vertical-lr");g.R3&&(h=h==="vertical-lr"?"tb-lr":"tb-rl");g.Ks(O,"-o-writing-mode",h);g.Ks(O,"-webkit-writing-mode",h);g.Ks(O,"writing-mode",h);g.Ks(O,"text-orientation","upright");g.qZ(O,"ytp-vertical-caption");D.K.params.T3===3&&(g.Ks(O,"text-orientation",""),g.Ks(O,"transform","rotate(180deg)"))},G_U=function(D){var O=1+.25*(D.fontSizeIncrement||0);
if(D.offset===0||D.offset===2)O*=.8;return O},Qo0=function(D,O){var h={},V=O.background?O.background:D.D.IK.background;
if(O.backgroundOpacity!=null||O.background){var k=O.backgroundOpacity!=null?O.backgroundOpacity:D.D.IK.backgroundOpacity;V=ezS(V);h.background="rgba("+V[0]+","+V[1]+","+V[2]+","+k+")";D.L1&&(h["box-decoration-break"]="clone",h["border-radius"]=D.Ax/8+"px")}if(O.fontSizeIncrement!=null||O.offset!=null)h["font-size"]=D.G2*G_U(O)+"px";V=1;k=O.color||D.D.IK.color;if(O.color||O.textOpacity!=null)k=ezS(k),V=O.textOpacity==null?D.D.IK.textOpacity:O.textOpacity,k="rgba("+k[0]+","+k[1]+","+k[2]+","+V+")",
h.color=k,h.fill=k;var C=O.charEdgeStyle;C===0&&(C=void 0);if(C){k="rgba(34, 34, 34, "+V+")";var M="rgba(204, 204, 204, "+V+")";O.aN&&(M=k=O.aN);var c=D.G2/16/2,S=Math.max(c,1),Y=Math.max(2*c,1),J=Math.max(3*c,1),q=Math.max(5*c,1);V=[];switch(C){case 4:for(;J<=q;J+=c)V.push(Y+"px "+Y+"px "+J+"px "+k);break;case 1:Y=window.devicePixelRatio>=2?.5:1;for(C=S;C<=J;C+=Y)V.push(C+"px "+C+"px "+k);break;case 2:V.push(S+"px "+S+"px "+M);V.push("-"+S+"px -"+S+"px "+k);break;case 3:for(J=0;J<5;J++)V.push("0 0 "+
Y+"px "+k)}h["text-shadow"]=V.join(", ")}k="";switch(O.fontFamily){case 1:k='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:k='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:k='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:k='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:k='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:k=g.xs()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:k='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}k&&(h["font-family"]=k);k=O.offset;k==null&&(k=D.D.IK.offset);switch(k){case 0:h["vertical-align"]="sub";break;case 2:h["vertical-align"]="super"}O.fontFamily===7&&(h["font-variant"]="small-caps");O.bold&&(h["font-weight"]="bold");O.italic&&(h["font-style"]="italic");O.underline&&(h["text-decoration"]=
"underline");O.qwF&&(h.visibility="hidden");O.Yp===1&&D.j&&(h["text-combine-upright"]="all",h["text-orientation"]="mixed",k=g.l8||g.Uk,D.K.params.T3===3?h.transform=k?"rotate(90deg)":"rotate(180deg)":k&&(h.transform="rotate(-90deg)"));if(O.vl===1||O.vl===2||O.vl===3||O.vl===4||O.vl===5)if(g.l8)h["font-weight"]="bold";else switch(h["text-emphasis-style"]="filled circle",h["text-emphasis-color"]="currentcolor",h["webkit-text-emphasis"]="filled circle",O.vl){case 4:case 3:h["text-emphasis-position"]=
"under left";h["webkit-text-emphasis-position"]="under left";break;case 5:case 2:h["text-emphasis-position"]="over right",h["webkit-text-emphasis-position"]="over right"}return h},us=function(D){D=D.split("px");
return D.length>0?(D=Number(D[0]))?D:0:0},wWc=function(D){D.T=g.CZ("SPAN");
g.Ks(D.T,{display:"block"});g.qZ(D.T,"caption-visual-line");D.W.appendChild(D.T)},soe=function(D,O){var h=g.CZ("SPAN");
g.Ks(h,{display:"inline-block","white-space":"pre-wrap"});g.Ks(h,Qo0(D,O));h.classList.add("ytp-caption-segment");D.T.appendChild(h);h.previousElementSibling&&(g.Ks(h.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Ks(h,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return h},WSL=function(D,O,h){D.X1=D.X1||!!h;
var V={};Object.assign(V,D.D.IK);Object.assign(V,h||O.D);Object.assign(V,D.Qy.IK);(h=!D.T)&&wWc(D);for(var k=D.ME&&D.ST&&g.T_(V,D.ST)?D.ME:soe(D,V),C=typeof O.text==="string",M=C?O.text.split("\n"):[O.text],c=0;c<M.length;c++){var S=c>0||!O.append,Y=M[c];S&&!h?(wWc(D),k=soe(D,V)):S&&h&&(h=!1);Y&&(k.appendChild(C?g.Mf(Y):Y),C||Y.tagName!=="RUBY"||Y.childElementCount!==4||g.l8||!g.jo(Y.children[2],"text-emphasis")||(S=D.j?"padding-right":"padding-top",g.jo(Y.children[2],"text-emphasis-position")&&(S=
D.j?"padding-left":"padding-bottom"),g.OL?g.Ks(k,S,"1em"):g.Ks(k,S,"0.5em")))}D.ST=V;D.ME=k;D.L.push(O)},Apc=function(D,O,h,V){var k=O/360*16;
O>=D&&(D=640,V>h*1.3&&(D=480),k=h/D*16);return k},dRc=function(){this.j=this.time=this.mode=this.K=0;
this.W=new TZc(this);this.J=new TZc(this);this.D=[];this.clear()},n$0=function(D,O,h){if(D===255&&O===255||!D&&!O)return{uE:D,
qD:O,result:0};D=zzx[D];O=zzx[O];if(D&128){var V;if(V=!(O&128))V=O,V=h.LW()&&h.qD===V;if(V)return{uE:D,qD:O,result:1}}else if(O&128&&1<=D&&D<=31)return{uE:D,qD:O,result:2};return{uE:D,qD:O,result:3}},ype=function(D,O,h,V){O===255&&h===255||!O&&!h?(++D.j===45&&D.reset(),D.W.K.clear(),D.J.K.clear()):(D.j=0,FSC(D.W,O,h,V))},i28=function(D,O){D.D.sort(function(k,C){var M=k.time-C.time;
return M===0?k.order-C.order:M});
for(var h=g.P(D.D),V=h.next();!V.done;V=h.next())V=V.value,D.time=V.time,V.type===0?ype(D,V.d4,V.R6,O):V.type===1&&D.K&496&&FSC(D.J,V.d4,V.R6,O);D.D.length=0},Hy=function(){this.type=0},mW=function(){this.state=this.qD=this.uE=0},rpR=function(){this.timestamp=this.D=0},eH=function(D){this.J=D;
this.j=[];this.D=this.K=this.row=0;this.style=new Hy;for(D=this.W=0;D<=15;D++){this.j[D]=[];for(var O=0;O<=32;O++)this.j[D][O]=new rpR}},L$=function(D,O){if(D.style.type===3){for(var h=0,V=0,k=D.J.time+0,C="",M="",c=k,S=1;S<=15;++S){for(var Y=!1,J=V?V:1;J<=32;++J){var q=D.j[S][J];
if(q.D!==0){h===0&&(h=S,V=J);Y=String.fromCharCode(q.D);var u=q.timestamp;u<k&&(k=u);q.timestamp=c;M&&(C+=M,M="");C+=Y;Y=!0}if((q.D===0||J===32)&&Y){M="\n";break}else if(V&&!Y)break}if(h&&!Y)break}C&&O.W(h,V,k,c,C)}else for(V=h=0,C=k=D.J.time+0,M=1;M<=15;++M)for(c="",S=1;S<=32;++S)if(J=D.j[M][S],q=J.D,q!==0&&(h===0&&(h=M,V=S),Y=String.fromCharCode(q),u=J.timestamp,u<=k&&(k=u),c+=Y,J.reset()),S===32||q===0)c&&O.W(h,V,k,C,c),k=C,c="",V=h=0},XWc=function(D,O){switch(D){case 0:return pW0[(O&127)-32];
case 1:return NZx[O&15];case 2:return o$R[O&31];case 3:return Z2S[O&31]}return 0},Py=function(D){return D.j[D.row][D.K]},gw=function(D,O,h){O>=2&&D.K>1&&(--D.K,Py(D).D=0);
var V=Py(D);V.timestamp=D.J.time+0;V.D=XWc(O,h);D.K<32&&D.K++},BZ8=function(D,O,h,V){for(var k=0;k<V;k++)for(var C=0;C<=32;C++){var M=D.j[O+k][C],c=D.j[h+k][C];
M.D=c.D;M.timestamp=c.timestamp}},Rp=function(D,O,h){for(var V=0;V<h;V++)for(var k=0;k<=32;k++)D.j[O+V][k].reset()},lpC=function(D){D.row=D.D>0?D.D:1;
D.K=1;Rp(D,0,15)},xRv=function(D){this.j=D;
this.J=0;this.style=new Hy;this.Z=new eH(this.j);this.L=new eH(this.j);this.text=new eH(this.j);this.K=this.Z;this.W=this.L;this.D=this.K},$Rx=function(D,O,h){var V=D.K,k=!1;
switch(D.style.get()){case 4:case 1:case 2:D.style.get()===4&&V.D>0||(L$(V,h),lpC(D.K),lpC(D.W),V.row=15,V.D=O,k=!0)}D.style.set(3);D.D=V;D.D.style=D.style;D.j.mode=1<<V.W;k?V.K=1:V.D!==O&&(V.D>O?(L$(V,h),Rp(V,V.row-V.D,O)):V.row<O&&(O=V.D),V.D=O)},IpL=function(D){D.style.set(1);
D.D=D.W;D.D.D=0;D.D.style=D.style;D.j.mode=1<<D.D.W},Dfv=function(D){D.style.set(4);
D.D=D.text;D.D.style=D.style;D.j.mode=1<<D.D.W},TZc=function(D){this.D=D;
this.J=0;this.j=new xRv(this.D);this.Z=new xRv(this.D);this.K=new mW;this.W=this.j},FSC=function(D,O,h,V){D.K.update();
O=n$0(O,h,D.K);switch(O.result){case 0:return;case 1:case 2:return}var k=O.uE;h=O.qD;if(32<=k||!k)D.D.mode&D.D.K&&(O=k,O&128&&(O=127),h&128&&(h=127),D=D.W.D,O&96&&gw(D,0,O),h&96&&gw(D,0,h),O!==0&&h!==0&&D.style.type===3&&L$(D,V));else if(k&16)a:if(!D.K.matches(k,h)&&(O=D.K,O.uE=k,O.qD=h,O.state=2,O=k&8?D.Z:D.j,D.W=O,D.D.mode=1<<(D.J<<2)+(O.J<<1)+(O.style.type===4?1:0),(D.D.mode|1<<(D.J<<2)+(O.J<<1)+(O.style.type!==4?1:0))&D.D.K))if(h&64){V=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(k&7)<<1|h>>5&1];
D=h&16?((h&14)>>1)*4:0;h=O.D;switch(O.style.get()){case 4:V=h.row;break;case 3:if(V!==h.row){if(V<h.D&&(V=h.D,V===h.row))break;var C=1+h.row-h.D,M=1+V-h.D;BZ8(h,M,C,h.D);O=C;k=h.D;M<C?(C=M+k-C,C>0&&(O+=C,k-=C)):(C=C+k-M,C>0&&(k-=C));Rp(h,O,k)}}h.row=V;h.K=D+1}else switch(k&7){case 1:switch(h&112){case 32:gw(O.D,0,32);break a;case 48:h===57?(V=O.D,Py(V).D=0,V.K<32&&V.K++):gw(O.D,1,h&15)}break;case 2:h&32&&gw(O.D,2,h&31);break;case 3:h&32&&gw(O.D,3,h&31);break;case 4:case 5:if(32<=h&&h<=47)switch(h){case 32:IpL(O);
break;case 33:V=O.D;V.K>1&&(--V.K,Py(V).D=0);break;case 36:V=O.D;O=Py(V);for(D=0;D<=15;D++)for(h=0;h<=32;h++)if(V.j[D][h]===O){for(;h<=32;h++)V.j[D][h].reset();break}break;case 37:$Rx(O,2,V);break;case 38:$Rx(O,3,V);break;case 39:$Rx(O,4,V);break;case 40:gw(O.D,0,32);break;case 41:O.style.set(2);O.D=O.K;O.D.D=0;O.D.style=O.style;O.j.mode=1<<O.D.W;break;case 42:V=O.text;V.D=15;V.style.set(4);lpC(V);Dfv(O);break;case 43:Dfv(O);break;case 44:D=O.K;switch(O.style.get()){case 1:case 2:case 3:L$(D,V)}Rp(D,
0,15);break;case 45:b:{D=O.D;switch(O.style.get()){default:case 2:case 1:break b;case 4:if(D.row<15){++D.row;D.K=1;break b}break;case 3:}D.D<2&&(D.D=2,D.row<D.D&&(D.row=D.D));O=D.row-D.D+1;L$(D,V);BZ8(D,O,O+1,D.D-1);Rp(D,D.row,1)}break;case 46:Rp(O.W,0,15);break;case 47:L$(O.K,V),O.W.updateTime(O.j.time+0),V=O.W,O.W=O.K,O.K=V,IpL(O)}break;case 7:switch(h){case 33:case 34:case 35:V=O.D,(V.K+=h&3)>32&&(V.K=32)}}},OZc=function(){},ap=function(D,O,h,V,k,C,M){C=C===void 0?!1:C;
M=M===void 0?null:M;g.S4.call(this,D,D+O,{priority:h,namespace:"captions"});this.windowId=V;this.text=k;this.append=C;this.D=M},VFv=function(D,O,h,V,k,C,M){var c=C[0],S=M[c.getAttribute("p")];
if(S.zd===1){var Y=C[1],J=C[2];C=C[3];c.getAttribute("t");Y.getAttribute("t");J.getAttribute("t");C.getAttribute("t");c.getAttribute("p");Y.getAttribute("p");C.getAttribute("p");M=M[J.getAttribute("p")];c=hoe(c.textContent,Y.textContent,J.textContent,C.textContent,M);return new ap(D,O,k,h,c,V,S)}switch(S.zd){case 9:case 10:S.vl=1;break;case 11:S.vl=2;break;case 12:S.vl=3;break;case 13:S.vl=4;break;case 14:S.vl=5}return new ap(D,O,k,h,c.textContent||"",V,S)},hoe=function(D,O,h,V,k){var C=g.xs(),M=
C?g.CZ("DIV"):g.CZ("RUBY"),c=g.CZ("SPAN");
c.textContent=D;M.appendChild(c);D=C?g.CZ("DIV"):g.CZ("RP");D.textContent=O;M.appendChild(D);O=C?g.CZ("DIV"):g.CZ("RT");O.textContent=h;M.appendChild(O);h=k.zd;if(h===10||h===11||h===12||h===13||h===14)if(g.Ks(O,"text-emphasis-style","filled circle"),g.Ks(O,"text-emphasis-color","currentcolor"),g.Ks(O,"webkit-text-emphasis","filled circle"),k.zd===11||k.zd===13)g.Ks(O,"webkit-text-emphasis-position","under left"),g.Ks(O,"text-emphasis-position","under left");h=!0;if(k.zd===4||k.zd===7||k.zd===12||
k.zd===14)g.Ks(M,"ruby-position","over"),g.Ks(M,"-webkit-ruby-position","before");else if(k.zd===5||k.zd===6||k.zd===11||k.zd===13)g.Ks(M,"ruby-position","under"),g.Ks(M,"-webkit-ruby-position","after"),h=!1;k=C?g.CZ("DIV"):g.CZ("RP");k.textContent=V;M.appendChild(k);C&&(V=h,g.Ks(M,{display:"inline-block",position:"relative"}),C=M.firstElementChild.nextElementSibling,g.Ks(C,"display","none"),C=C.nextElementSibling,g.Ks(C,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Ks(M.lastElementChild,"display","none"),V?(g.Ks(M,"padding-top","0.6em"),g.Ks(C,"top","0")):(g.Ks(M,"padding-bottom","0.6em"),g.Ks(C,"bottom","0")));return M},f$=function(){g.n.apply(this,arguments)},K$=function(D,O,h,V,k){g.S4.call(this,D,D+O,{priority:h,
namespace:"captions"});this.id=V;this.params=k;this.D=[]},kG8=function(D){var O="_"+Ev++;
return new K$(0,0x8000000000000,0,O,D)},jH=function(D){f$.call(this);
this.j=D;this.pens={};this.L={};this.T={};this.W="_"+Ev++;this.Z={};this.K=this.D=null;this.J=!0},Uv=function(D,O){D=D.getAttribute(O);
if(D!=null)return Number(D)},Am=function(D,O){D=D.getAttribute(O);
if(D!=null)return D==="1"},Gw=function(D,O){D=Uv(D,O);
return D!==void 0?D:null},vy=function(D,O){D=D.getAttribute(O);
if(D!=null)return tm.test(D),D},C3U=function(D,O){var h={},V=O.getAttribute("ws");
Object.assign(h,V?D.T[V]:D.j);D=Gw(O,"mh");D!=null&&(h.C5=D);D=Gw(O,"ju");D!=null&&(h.textAlign=D);D=Gw(O,"pd");D!=null&&(h.T3=D);D=Gw(O,"sd");D!=null&&(h.tJ=D);D=vy(O,"wfc");D!=null&&(h.windowColor=D);O=Uv(O,"wfo");O!==void 0&&(h.windowOpacity=O/255);return h},MF_=function(D,O){var h={},V=O.getAttribute("wp");
V&&Object.assign(h,D.L[V]);D=Gw(O,"ap");D!=null&&(h.zo=D);D=Uv(O,"cc");D!=null&&(h.cR=D);D=Uv(O,"ah");D!=null&&(h.k_=D);D=Uv(O,"rc");D!=null&&(h.dC=D);O=Uv(O,"av");O!=null&&(h.C3=O);return h},bZS=function(D,O,h,V){var k={};
Object.assign(k,MF_(D,O));Object.assign(k,C3U(D,O));V?g.T_(k,D.j)?(V=D.W,k=D.j):V="_"+Ev++:V=O.getAttribute("id")||"_"+Ev++;D=Uv(O,"t")+h;O=Uv(O,"d")||0x8000000000000;if(k.T3===2||k.T3===3)h=k.dC,k.dC=k.cR,k.cR=h;return new K$(D,O,0,V,k)},QH=function(D){f$.call(this);
this.J=D;this.D=new Map;this.j=new Map;this.W=new Map;this.K=new Map},ww=function(D){D=g.mS(Math.round(D),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-D.length)+D},cJJ=function(D,O,h,V,k){V===0&&(V=0x8000000000000);
var C={};O.wpWinPosId&&Object.assign(C,D.j.get(O.wpWinPosId));O.wsWinStyleId&&Object.assign(C,D.W.get(O.wsWinStyleId));D=O.rcRowCount;D!==void 0&&(C.dC=D);O=O.ccColCount;O!==void 0&&(C.cR=O);if(C.T3===2||C.T3===3)O=C.dC,C.dC=C.cR,C.cR=O;return new K$(h,V,0,k,C)},Wy=function(D,O,h){g.nu.call(this,D);
this.videoData=O;this.audioTrack=h;this.J=O.P5},Tw=function(D,O,h,V,k,C,M,c,S,Y){qE.call(this,D,O,h,V,k,C,M,c,S,Y);
this.type=1},dw=function(D,O,h){this.trackData=D;
this.Z=h;this.version=this.J=this.j=this.byteOffset=0;this.K=[];this.D=new DataView(this.trackData)},zw=function(D){var O=D.byteOffset;
D.byteOffset+=1;return D.D.getUint8(O)},n$=function(D){var O=D.byteOffset;
D.byteOffset+=4;return D.D.getUint32(O)},Fr=function(D,O){f$.call(this);
this.K=D;this.j=O;this.track=this.j.languageName==="CC3"?4:0;this.D=new dRc;this.D.K=1<<this.track},YLc=function(D){if(typeof D==="string")return!1;
D=new dw(D,8,0);return SLc(D)},SLc=function(D){if(!(D.byteOffset<D.D.byteLength)||n$(D)!==1380139777)return!1;
D.version=zw(D);if(D.version>1)return!1;zw(D);zw(D);zw(D);return!0},yH=function(D,O,h,V,k,C,M,c,S,Y){qE.call(this,D,O,h,V,k,C,M,c,S,Y);
var J=this;this.type=2;this.lS=[];this.Ew=this.U=this.LF=0;this.qE=NaN;this.C1=0;this.bb=null;this.Vi=new g.kF(this.Ia7,433,this);this.J&&(Y.createClientVe(this.J,this,167342),this.G(this.J,"click",function(){Y.logClick(J.J)}),D=new g.ST(this.element,!0),g.F(this,D),D.subscribe("hoverstart",function(){Y.logVisibility(J.J,!0)},this));
g.qZ(this.element,"ytp-caption-window-rollup");g.F(this,this.Vi);g.Ks(this.element,"overflow","hidden")},JJm=function(D,O){if(!O)return"";
D.j&&D.K.params.tJ!==1&&(O*=-1);return"translate"+(D.j?"X":"Y")+"("+O+"px)"},qLS=function(D){D.lS=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var O=D.K.params.dC,h=0,V=0,k=D.lS.length-1;h<O&&k>-1;){var C=D.lS[k];V+=D.j?C.offsetWidth:C.offsetHeight;h++;k--}D.U=V;O=Math;h=O.max;isNaN(D.qE)&&((V=D.D.cR)?(k=g.CZ("SPAN"),g.qf(k,"\u2013".repeat(V)),g.Ks(k,Qo0(D,D.D.IK)),D.W.appendChild(k),D.qE=k.offsetWidth,D.W.removeChild(k)):D.qE=0);V=D.W;D.Ew=h.call(O,D.qE,D.C1,(D.j?V.offsetHeight:V.offsetWidth)+1)},u0R=function(D,O){qLS(D);
var h=D.lS.reduce(function(C,M){return(D.j?M.offsetWidth:M.offsetHeight)+C},0);
h=D.U-h;if(h!==D.LF){var V=h>0&&D.LF===0,k=h<D.LF;O||isNaN(h)||V||!k||(g.qZ(D.element,"ytp-rollup-mode"),g.Cd(D.Vi));g.Ks(D.W,"transform",JJm(D,h));D.LF=h}qLS(D)},HZ8=function(D,O){g.nu.call(this,O);
this.K=D;this.C=O;this.logger=new g.m3("caps");this.j=this.Z=this.L=null},mfv=function(D,O,h,V){D.logger.debug(function(){return"SABR captions data received for "+V});
D.L?D.Z==null?D.logger.D(350058965,"Null loaded track meta data at captions data received"):h.bC(O,D.Z,(V+D.C.Uv())*1E3):D.logger.D(350058965,"Null Representation at captions data received")},eom=function(D,O){var h=[],V;
for(V in D.K.D)if(D.K.D.hasOwnProperty(V)){var k=D.K.D[V];if(g.yr(k,O||null)){var C=k.info.id,M=C,c="."+C,S="",Y="";if(k=k.info.captionTrack)C=k.languageCode,M=k.displayName,c=k.vssId,S=k.kind,Y=k.id;h.push(new g.Yi({id:V,languageCode:C,languageName:M,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:c,kind:S,captionId:Y}))}}return h},Lx9=function(D,O){return O!=null&&O in D.K.D?D.K.D[O]:null},P3m=function(D,O,h){var V=[],k;
for(k in D.K.D)if(D.K.D.hasOwnProperty(k)){var C=D.K.D[k];if(g.yr(C,h||null)){var M=C.info.captionTrack;M&&M.languageCode===O&&V.push(C)}}return V.length?V[0]:null},ge8=function(D,O){if(!D.S("html5_enable_sabr_live_captions")||D.D!=null&&g.v5(O.V())&&!D.D.isManifestless&&D.D.D.rawcc!=null||!D.k5())return!1;
O=!!D.D&&D.D.isManifestless&&Object.values(D.D.D).some(function(h){return g.yr(h,"386")});
D=!!D.D&&!D.D.isManifestless&&g.Gjy(D.D);return O||D},is=function(){f$.call(this)},Rov=function(D,O,h,V,k,C,M,c,S){switch(M.tagName){case "b":c.bold=!0;
break;case "i":c.italic=!0;break;case "u":c.underline=!0}for(var Y=0;Y<M.childNodes.length;Y++){var J=M.childNodes[Y];if(J.nodeType===3)J=new ap(O,h,V,k.id,J.nodeValue,C||Y>0,g.sO(c)?void 0:c),S.push(J),k.D.push(J);else{var q={};Object.assign(q,c);Rov(D,O,h,V,k,!0,J,q,S)}}},a9U=function(D){var O=D.split(":");
D=0;O=g.P(O);for(var h=O.next();!h.done;h=O.next())D=D*60+Number(h.value);return D*1E3},f9x=function(D,O,h,V){V=Object.assign({C5:0},V);
return new K$(D,O,h,"_"+Ev++,V)},rw=function(D,O){g.n.call(this);
this.C=D;this.D8=O;this.D=null;this.K=this.C.zX();this.logger=new g.m3("caps")},Eex=function(D,O,h){if(typeof O==="string"||YLc(O))return[{trackData:O,
Bm:h}];var V=new DataView(O);if(V.byteLength<=8||V.getUint32(4)!==1718909296)return[];var k=g.fSy(V);if(D.K&&k){var C=g.HFq(k),M=g.m1B(k);k=k.zb;C&&k&&D.K.au(k,C,M)}D=g.Ik(V,1835295092);if(!D||!D.length||!D[0].size)return[];C=[];for(M=0;M<D.length;M++)k=D[M],k=new Uint8Array(O,k.dataOffset,k.size-(k.dataOffset-k.offset)),k=g.ya(k),C.push({trackData:k,Bm:h+M*1E3});KxR(V,C,h);return C=C.filter(function(c){return!!c.trackData})},KxR=function(D,O,h){var V=g.p5(D,0,1836476516),k=9E4;
V&&(k=g.NS(V)||9E4);V=0;for(var C=g.Ik(D,1836019558),M=0;M<C.length;M++){var c=C[M];M<O.length&&(c=g.p5(D,c.dataOffset,1953653094))&&(c=g.p5(D,c.dataOffset,1952867444))&&(c=g.xL(c)/k*1E3,M===0&&(V=c),O[M].Bm=c-V+h||h*M*1E3)}},jrC=function(D){var O={};
if(D=g.uE(D))O.lang=D,g.C_m.test(D)&&(O.T3=1);return O},p$=function(D){g.dX.call(this,D);
var O=this;this.C=D;this.ME=[];this.lS={};this.Vi={};this.T=!1;this.W="NONE";this.D=this.U=this.Ew=this.G2=this.m5=null;this.C1={Yy:function(){O.Yy()},
bC:function(C,M,c,S){O.bC(C,M,c,S)}};
this.K=null;this.D8=this.C.V();this.videoData=this.C.getVideoData();this.Uw=this.C.B3();var h;this.oW=(h=this.C.getVideoData(1))==null?void 0:g.h4(h);this.j={IK:{}};this.Z={IK:{}};g.uA(this.videoData)?this.W="OFFLINE":ge8(this.videoData,this.C)?this.W="SABR_LIVE":g.OxR(this.videoData,this.C)?this.W="LIVE":this.videoData.captionTracks.length?this.W="INNERTUBE":this.videoData.RK&&(this.W="TTS");this.Ax=this.D8.controlsType==="3";this.T2=new rw(this.C,this.D8);this.qE=new g.yp(this);this.L=new g.N({X:"div",
Y:"ytp-caption-window-container",B:{id:"ytp-caption-window-container"}});this.jT={top:0,right:0,bottom:0,left:0,width:1,height:1};h=null;var V=g.rC("yt-html5-player-modules::subtitlesModuleData");V&&(h=new g.sV(V));this.storage=h;var k;this.yy=!((k=D.eg())==null||!k.ZQ());this.J=UfJ(this);this.X1=!this.J&&this.Ax&&this.yy&&(this.W==="LIVE"||this.W==="SABR_LIVE");g.F(this,this.T2);this.J?this.LF=this.ST=null:(this.ST=new g.VQ(this.Xy,void 0,this),g.F(this,this.ST),this.LF=new g.kF(this.oGw,2E3,this),
g.F(this,this.LF));g.F(this,this.qE);g.BR(this.player,this.L.element,4);g.F(this,this.L);this.J||this.qE.G(D,"resize",this.SM);(this.f1=g.v_(this.D8)&&!g.KJ()&&!this.C.isFullscreen()&&!this.J&&!this.X1)&&this.qE.G(D,"resize",this.XFF);this.qE.G(D,"onPlaybackAudioChange",this.kqr);this.qE.G(D,g.J6("captions"),function(C){O.onCueRangeEnter(C)});
this.qE.G(D,g.q1("captions"),function(C){O.onCueRangeExit(C)});
this.oW&&this.qE.G(D,"videodatachange",function(C,M){O.onVideoDataChange(C,M)});
AJx(this,Ple()||{});this.player.VH("onCaptionsModuleAvailable")},ve9=function(D){if(D.D8.f1===1||D.videoData.In===1||g.KO(D.videoData,"yt:cc")==="alwayson")return!0;
if(D.videoData.captionTracks.length)var O=D.getAudioTrack().K;if(D.D8.f1===2){if(g.Z$(D.D8))var h=GG_(D);else if(D.storage)try{h=D.storage.get("module-enabled")}catch(k){D.storage.remove("module-enabled")}else h=null;if(h!=null)return!!h}h=SOC(D.player.getAudioTrack(),g.Z$(D.D8));var V=g.KO(D.videoData,"yt:cc");if(tF_(D)===void 0){if(h==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return V?V==="on":!0;if(h==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return V==="on"}else return V==="on";return O==="ON"||
g.KO(D.videoData,"yt:cc")==="on"},NE=function(D,O){if(D.K&&(O===void 0||!O)||!D.videoData.captionTracks.length)return!1;
D=D.getAudioTrack();return!!D.D||D.K==="FORCED_ON"},tF_=function(D){var O=void 0,h=g.BU(g.X4(),65);
if(g.Z$(D.D8)&&h!=null){if(GG_(D)!=null)return!1;O=!h}return O},Z5=function(D,O){if(!D.D)return null;
if(D.U&&D.U.W)return D.U.W;O=Qr8(D,O);O=g.E7(D.D.D,O);var h=null;if(YO_(D.D8)){var V=D.C.isInline()?void 0:g.i0("yt-player-caption-sticky-language");for(var k=[V,D.videoData.captionsLanguagePreference,D.D8.captionsLanguagePreference,g.KO(D.videoData,"yt:cc_default_lang")],C=!1,M=0;M<k.length;M++){var c=k[M];if(c){C=!0;for(var S=0;S<O.length;S++)if(g.uE(O[S])===c)return O[S];for(S=0;S<O.length;S++)if(g.uE(O[S]).split("-")[0]===c.split("-")[0])return O[S]}}if(C&&D.D&&(k=D.D.J,k.length))for(k=g.P(k),
C=k.next();!C.done;C=k.next())if(C=C.value,C.languageCode===V){h=C;break}}else for(V=[D.videoData.captionsLanguagePreference,D.D8.captionsLanguagePreference,g.KO(D.videoData,"yt:cc_default_lang")],k=0;k<V.length;k++)for(C=0;C<O.length;C++)if(g.uE(O[C])===V[k])return O[C];V=null;D.U&&D.U.j&&(V=D.U.j);V||(V=O.find(function(Y){return Y.isDefault})||null);
V||(V=O[0]||op(D));V&&h&&g.uE(V).split("-")[0]!==h.languageCode.split("-")[0]&&(V=JpR(V,h));return V},op=function(D){return D.U&&D.U.D},Xr=function(D){var O=op(D);
return!!O&&D.K===O},wj0=function(D,O){var h=D.C.eg().JU().textTracks;
D=D.K.toString();for(var V=0;V<h.length;V++){var k=h[V];k.id===D&&(O?k.mode!=="showing"&&(k.mode="showing"):k.mode==="showing"&&(k.mode="disabled"))}},xQ=function(D,O,h){D.loaded&&D.unload();
h!=null&&(D.T=h,D.T&&(g.Z$(D.D8)?By(D,!!O):ls(D,!!O)));D.D8.S("html5_report_caption_format_change")&&srC(D,D.K,O,D.T,!1);D.K=O;NE(D)&&(O=op(D),D.D8.S("html5_report_caption_format_change")&&srC(D,D.K,O,D.T,!0),D.K=O);var V;Wx8(D,(V=D.K)!=null?V:void 0);D.load()},dfC=function(D,O){if(O instanceof K$){var h=D.lS[O.id];
h&&h.K!==O&&(h.dispose(),delete D.lS[O.id],h=null);h||(h=TjL(D,O))&&(D.lS[O.id]=h)}else h=O.windowId,D.Vi[h]||(D.Vi[h]=[]),D.Vi[h].push(O)},TjL=function(D,O){var h=zoR(D);
if(!h)return null;var V=D.K?g.uE(D.K):null;V&&g.C_m.test(V)&&(O.params.T3=1);var k=D.Uw.getPlayerSize();V=k.height*D.jT.height;k=k.width*D.jT.width;D.D8.playerStyle!=="google-live"||D.j.isDefault||Object.assign(O.params,D.j);switch(O.params.C5!=null?O.params.C5:O.D.length>1?1:0){case 1:return new Tw(O,D.j,D.Z,h.width,h.height,k,V,D.D8.experiments,D.WL.bind(D),D.C);case 2:return new yH(O,D.j,D.Z,h.width,h.height,k,V,D.D8.experiments,D.WL.bind(D),D.C);default:return new qE(O,D.j,D.Z,h.width,h.height,
k,V,D.D8.experiments,D.WL.bind(D),D.C)}},AJx=function(D,O,h){h=h===void 0?!1:h;
var V=$Q.IK;D.j={};Object.assign(D.j,$Q);D.j.IK={};Object.assign(D.j.IK,V);D.Z={IK:{}};var k=O.backgroundOverride?D.Z:D.j,C=O.background||V.background;tm.test(C);k.IK.background=C;k=O.colorOverride?D.Z:D.j;C=O.color||V.color;tm.test(C);k.IK.color=C;k=O.windowColorOverride?D.Z:D.j;C=O.windowColor||$Q.windowColor;tm.test(C);k.windowColor=C;k=O.backgroundOpacityOverride?D.Z:D.j;C=O.backgroundOpacity;C==null&&(C=V.backgroundOpacity);k.IK.backgroundOpacity=C;k=O.fontSizeIncrementOverride?D.Z:D.j;C=O.fontSizeIncrement;
C==null&&(C=V.fontSizeIncrement);k.IK.fontSizeIncrement=C;C=O.fontStyleOverride?D.Z:D.j;k=O.fontStyle;k==null&&(k=V.bold&&V.italic?3:V.bold?1:V.italic?2:0);C=C.IK;switch(k){case 1:C.bold=!0;delete C.italic;break;case 2:delete C.bold;C.italic=!0;break;case 3:C.bold=!0;C.italic=!0;break;default:delete C.bold,delete C.italic}k=O.textOpacityOverride?D.Z:D.j;C=O.textOpacity;C==null&&(C=V.textOpacity);k.IK.textOpacity=C;k=O.windowOpacityOverride?D.Z:D.j;C=O.windowOpacity;C==null&&(C=$Q.windowOpacity);k.windowOpacity=
C;k=O.charEdgeStyleOverride?D.Z:D.j;C=O.charEdgeStyle;C==null&&(C=V.charEdgeStyle);k.IK.charEdgeStyle=C;k=O.fontFamilyOverride?D.Z:D.j;C=O.fontFamily;C==null&&(C=V.fontFamily);k.IK.fontFamily=C;D.loaded&&D.SM();h&&g.yu("yt-player-caption-display-settings",O,2592E3)},nev=function(D,O){if(!D.D)return{};
if(O){D.D8.S("html5_report_caption_format_intent")&&!g.sO(O)&&D.V8(O.vss_id,"m");if(D.J||!g.pT(O))return;if(g.sO(O)){xQ(D,null,!0);return}for(var h,V=g.E7(D.D.D,!0),k=0;k<V.length;k++){var C=V[k];C.languageCode!==O.languageCode||h&&(C.languageName!==O.languageName||(C.captionId||"")!==(O.captionId||"")||g.J1(C)!==O.displayName)||(h=O.translationLanguage?JpR(C,O.translationLanguage):C)}D.Ak(O.position);!h||h===D.K&&D.loaded||(O=g.ix(),V=g.uE(h),O.length&&V===O[O.length-1]||(O.push(V),g.yu("yt-player-caption-language-preferences",
O)),YO_(D.D8)&&!D.C.isInline()&&g.yu("yt-player-caption-sticky-language",V,2592E3),xQ(D,h,!0))}else return D.loaded&&D.K&&!Xr(D)?g.qv(D.K):{};return""},yJv=function(D,O,h){O&&!D.Ew?(O=kG8({T3:0,
lang:"en-GB"}),D.Ew=[O,new ap(O.start,O.end-O.start,0,O.id,h!=null?h:"Captions look like this")],D.player.nW(D.Ew)):!O&&D.Ew&&(Fxm(D,D.Ew),D.Ew=null)},Fxm=function(D,O){D.player.FD(O);
O=g.P(O);for(var h=O.next();!h.done;h=O.next())g.xC(D.ME,h.value);SH(D.ST)},Wx8=function(D,O){D.D8.S("html5_modify_caption_vss_logging")&&(D.videoData.mf=O)},zoR=function(D){var O=D.Uw.getVideoContentRect(!0).height,h=D.Uw.getVideoContentRect(!0).width;
if(!O||!h)return null;O*=D.jT.height;h*=D.jT.width;return{width:h,height:O}},ls=function(D,O){if(D.storage)try{D.storage.set("module-enabled",O)}catch(h){}},By=function(D,O){D.C.isInline()||g.yu("yt-player-sticky-caption",O,2592E3)},GG_=function(D){if(!D.C.isInline())return g.i0("yt-player-sticky-caption")},UfJ=function(D){var O,h=!((O=D.C.eg())==null||!O.wO());
return D.Ax&&h&&D.W!=="LIVE"&&D.W!=="SABR_LIVE"},Qr8=function(D,O){g.ka(D.videoData)&&(O=!0);
O||(O=D.W==="TTS"?!1:D.W==="INNERTUBE"?!1:!0);return O||D.D8.S("web_deprecate_always_includes_asr_setting")&&g.Z$(D.D8)?!0:!!g.BU(g.X4(),66)},srC=function(D,O,h,V,k){k?D.o0(h,!0,"g"):V?O?D.o0(h,!!h,"m"):h&&D.o0(h,!0,"m"):!O&&h&&D.o0(h,!0,"s")};
g.nu.prototype.du=g.V_(63,function(){return!1});
g.nu.prototype.mK=g.V_(62,function(){});
g.FU.prototype.mK=g.V_(61,function(D,O,h){var V=this;this.Z8();O=this.Aj(D,O);var k=this.aW.V().S("html5_report_captions_ctmp_qoe"),C=(0,g.Ws)();this.Hl();cpR(this,O,{format:"RAW",onSuccess:function(M){V.K=null;if(k){var c=(M.responseText.length/1024).toFixed(),S=(0,g.Ws)();V.videoData.KF("capresp",{ms:S-C,kb:c})}h.bC(M.responseText,D)},
onError:k?function(M){var c;M=(c=M==null?void 0:M.status)!=null?c:0;V.videoData.KF("capfail",{status:M})}:void 0,
withCredentials:!0})});
g.i9.prototype.mK=g.V_(60,function(D,O,h){var V=this;this.Z8();O=this.Aj(D,O);this.Hl();this.K=g.wt(O,{format:"RAW",onSuccess:function(k){V.K=null;h.bC(k.responseText,D)},
withCredentials:!0})});
g.Lu.prototype.bI=g.V_(59,function(){for(var D=g.$$(document,"track",void 0,this.D),O=0;O<D.length;O++)g.Ye(D[O])});
g.p4.prototype.bI=g.V_(58,function(){this.mediaElement.bI()});
g.Lu.prototype.ZQ=g.V_(57,function(){return!(!this.D.textTracks||!this.D.textTracks.addEventListener)});
g.p4.prototype.ZQ=g.V_(56,function(){return this.mediaElement.ZQ()});
g.Lu.prototype.wO=g.V_(55,function(){return!!this.D.textTracks});
g.p4.prototype.wO=g.V_(54,function(){return this.mediaElement.wO()});
g.Lu.prototype.H7=g.V_(53,function(D){for(var O=0;O<D.length;O++)this.D.appendChild(D[O])});
g.p4.prototype.H7=g.V_(52,function(D){this.mediaElement.H7(D)});
g.fG.prototype.au=g.V_(47,function(D,O,h){this.RM.au(D,O,h)});
g.IE.prototype.au=g.V_(46,function(D,O,h){this.ST.set(D,{eZ:O,HX:h})});
g.fG.prototype.wy=g.V_(45,function(D){return this.RM.wy(D)});
g.IE.prototype.wy=g.V_(44,function(D){var O=2;this.Z.has(D)?O=0:g.dNk(this,D)&&(O=1);return O});
g.m3.prototype.D=g.V_(43,function(D){g.eUB.apply(null,[5,this.tag,D].concat(g.a(g.GR.apply(1,arguments))))});
g.yD.prototype.Fs=g.V_(42,function(D){var O=g.wL(this.app);return O?O.Fs(D):!1});
g.kc.prototype.Fs=g.V_(41,function(D){return this.M2().some(function(O){return O.namespace===D})});
g.Cg.prototype.Fs=g.V_(40,function(D){return this.tx.Db.Fs(D)});
g.yD.prototype.V8=g.V_(38,function(D,O){var h;(h=this.app.nF())==null||h.V8(D,O)});
g.y1.prototype.V8=g.V_(37,function(D,O){D=[D,O];g.FT(this,g.dn(this.provider),"cfi",D)});
g.O0.prototype.V8=g.V_(36,function(D,O){this.qoe&&this.qoe.V8(D,O)});
g.Cg.prototype.V8=g.V_(35,function(D,O){this.tx.V8(D,O)});
g.G2.prototype.V8=g.V_(34,function(D,O){this.aT().V8(D,O)});
g.yD.prototype.o0=g.V_(33,function(D,O,h){var V;(V=this.app.nF())==null||V.o0(D,O,h)});
g.y1.prototype.o0=g.V_(32,function(D,O,h){if(this.ST!==D||this.bb!==O)O=O==="rawcc"?"":O,h=[D,O,this.ST,h],g.FT(this,g.dn(this.provider),"cfs",h),this.ST=D,this.bb=O});
g.O0.prototype.o0=g.V_(31,function(D,O,h){this.qoe&&this.qoe.o0(D,O,h)});
g.Cg.prototype.o0=g.V_(30,function(D,O,h){this.tx.o0(D,O,h)});
g.G2.prototype.o0=g.V_(29,function(D,O,h){this.aT().o0(D,O,h)});
g.PH.prototype.p4=g.V_(18,function(){return this.T});
g.Kx.prototype.p4=g.V_(17,function(){var D;return((D=this.NS())==null?void 0:D.zX())||null});
g.yD.prototype.zX=g.V_(16,function(){return this.app.p4()});
g.G2.prototype.zX=g.V_(15,function(){var D;return((D=this.IW)==null?void 0:D.p4())||null});
g.tt.prototype.KC=g.V_(1,function(D){return(D=this.gq(D))?D.D:0});
g.V6.prototype.KC=g.V_(0,function(){return 0});
var mRU=/#(.)(.)(.)/,H2U=/^#(?:[0-9a-f]{3}){1,2}$/i,KSm={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};YQ.prototype.contains=function(D){D=g.Mt(this.segments,D);return D>=0||D<0&&(-D-1)%2===1};
YQ.prototype.length=function(){return this.segments.length/2};
g.e(RzS,g.n);g.b=RzS.prototype;g.b.fF=function(){g.n.prototype.fF.call(this);this.j&&this.j.cancel()};
g.b.Rm=function(){this.seekTo(this.player.getCurrentTime())};
g.b.seekTo=function(D){D-=this.player.Uv();var O=this.D;this.D=g.N9(this.Ew.Gr(D).ra);O!==this.D&&this.U&&this.U()};
g.b.reset=function(){this.W=new YQ;this.Z=-1;this.j&&(this.j.cancel(),this.j=null)};
g.b.dG=function(){this.Z8();var D;if(D=this.D!=null)D=this.D,D=D.D.tj(D);if(D&&!this.j&&!(this.D&&this.D.startTime-this.player.getCurrentTime()>30)){D=this.D;D=D.D.St(D);var O=D.ra[0],h;if((h=this.player.getVideoData())==null?0:h.enableServerStitchedDai)if(h=this.player.zX()){var V=O.D.info.id,k=O.hx,C=D.ra[0].r0;if(this.policy.ST){if(h=h.IV(C,k,V,3))D.W=h}else if(V=h.Ea(C,k,V,3))if(h=h.wy(k),h===0)V&&(D.D=new g.ak(V));else if(h===2){this.L.start();ap_(this)&&this.seekTo(this.player.getCurrentTime());
return}}O.D.index.V6(O.hx)?(this.W.contains(D.ra[0].hx)||fpx(this,D),this.D=g.N9(D.ra)):ap_(this)&&this.seekTo(this.player.getCurrentTime())}this.L.start()};
g.e(Jm,g.nu);g.b=Jm.prototype;g.b.mK=function(D,O,h){var V=this;this.Hl();O=jox(this,D.getId());O||(O=D.languageCode,O=this.K.isManifestless?URJ(this,O,"386"):URJ(this,O));if(O){var k=(O.index.KC(O.index.Li())-O.index.getStartTime(O.index.Li()))*1E3,C=this.C.V(),M=new g.UoP(C),c=function(){V.j&&V.j.reset();V.Z=!0};
C.S("html5_keep_caption_data_after_seek")&&(c=null);this.j=new RzS(M,this.C,O,function(S,Y){h.bC(S,D,Y,k)},this.L||g.OC(O.info),c)}};
g.b.du=function(){var D=this.Z;this.Z=!1;return D};
g.b.aU=function(D){var O=this.L?[new g.Yi({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Yi({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.K.isManifestless?E$0(this,"386"):E$0(this);O=g.P(O);for(var h=O.next();!h.done;h=O.next())g.zP(this.D,h.value);D.Yy()};
g.b.Hl=function(){this.j&&(this.j.dispose(),this.j=null)};
g.b.Aj=function(){return""};
g.b.eL=function(){this.j&&(this.j.reset(),this.C.Y8("captions"))};
var tm=/^#(?:[0-9a-f]{3}){1,2}$/i;var trL=["left","right","center","justify"];g.e(qE,g.N);g.b=qE.prototype;g.b.CP=function(D,O){this.T2=D;this.oW=O;var h=g.wJ(this.element,this.element.parentElement);this.m5=D-h.x;this.Uw=O-h.y};
g.b.XA=function(D,O){if(D!==this.T2||O!==this.oW){g.JX(this.element,"ytp-dragging")||g.qZ(this.element,"ytp-dragging");var h=g.Wt(this.element);D=D-this.m5-.02*this.playerWidth;var V=O-this.Uw-.02*this.playerHeight,k=(D+h.width/2)/this.maxWidth*3;k=Math.floor(g.mS(k,0,2));var C=(V+h.height/2)/this.maxHeight*3;C=Math.floor(g.mS(C,0,2));O=k+C*3;D=(D+k/2*h.width)/this.maxWidth;D=g.mS(D,0,1)*100;h=(V+C/2*h.height)/this.maxHeight;h=g.mS(h,0,1)*100;this.K.params.zo=O;this.K.params.C3=h;this.K.params.k_=
D;this.K.params.isDefault=!1;this.D.zo=O;this.D.C3=h;this.D.k_=D;this.D.isDefault=!1;this.jT.zo=O;this.jT.C3=h;this.jT.k_=D;this.jT.isDefault=!1;this.xU()}};
g.b.cV=function(){g.Hk(this.element,"ytp-dragging")};
g.b.xU=function(){this.c_(this.L)};
g.b.getType=function(){return this.type};
g.b.c_=function(D){var O=this.f1?0:Math.min(this.bH(),this.maxWidth),h=this.Yt(),V=this.f1;if(V){var k=getComputedStyle(this.W.parentNode);k=us(k.borderLeftWidth)+us(k.borderRightWidth)+us(k.paddingLeft)+us(k.paddingRight)}else k=0;var C=k;k="";this.K.params.T3===3&&(k="rotate(180deg)");var M=V?"calc(96% - "+C+"px)":"96%";g.Ks(this.element,{top:0,left:0,right:"",bottom:"",width:O?O+"px":"",height:h?h+"px":"","max-width":M,"max-height":M,margin:"",transform:""});this.lj(D);k={transform:k,top:"",left:"",
width:O?O+"px":"",height:h?h+"px":"","max-width":"","max-height":""};var c=this.D.k_*.96+2;M=this.D.zo;switch(M){case 0:case 3:case 6:(V=this.D.IK.fontSizeIncrement)&&V>0&&this.D.T3!==2&&this.D.T3!==3&&(c=Math.max(c/(1+V*2),2));k.left=c+"%";break;case 1:case 4:case 7:k.left=c+"%";c=this.W.offsetWidth;O||c?(O=O||c+1,k.width=O+"px",k["margin-left"]=V?O/-2-C/2+"px":O/-2+"px"):k.transform+=" translateX(-50%)";break;case 2:case 5:case 8:k.right=100-c+"%"}V=this.D.C3*.96+2;switch(M){case 0:case 1:case 2:k.top=
V+"%";break;case 3:case 4:case 5:k.top=V+"%";(h=h||this.element.clientHeight)?(k.height=h+"px",k["margin-top"]=h/-2+"px"):k.transform+=" translateY(-50%)";break;case 6:case 7:case 8:k.bottom=100-V+"%"}g.Ks(this.element,k);if(this.J){h=this.W.offsetHeight;V=1;for(O=0;O<D.length;O++)k=D[O],typeof k.text==="string"&&(V+=k.text.split("\n").length-1,k.append||O===0||V++);h/=V;this.J.style.height=h+"px";this.J.style.width=h+"px";this.element.style.paddingLeft=h+5+"px";this.element.style.paddingRight=h+
5+"px";D=Number(this.element.style.marginLeft.replace("px",""))-h-5;h=Number(this.element.style.marginRight.replace("px",""))-h-5;this.element.style.marginLeft=D+"px";this.element.style.marginRight=h+"px"}};
g.b.lj=function(D){var O;for(O=0;O<D.length&&D[O]===this.L[O];O++);if(this.X1||this.L.length>O)O=0,this.X1=!1,this.L=[],this.T=this.ST=this.ME=null,g.cj(this.W);for(;O<D.length;O++)WSL(this,D[O])};
g.b.bH=function(){return 0};
g.b.Yt=function(){return 0};
g.b.toString=function(){return g.N.prototype.toString.call(this)};dRc.prototype.clear=function(){this.j=this.time=this.mode=0;this.D=[];this.reset()};
dRc.prototype.reset=function(){this.mode=0;this.W.reset(0);this.J.reset(1)};
var zzx=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];Hy.prototype.set=function(D){this.type=D};
Hy.prototype.get=function(){return this.type};
mW.prototype.clear=function(){this.state=0};
mW.prototype.update=function(){this.state=this.state===2?1:0};
mW.prototype.LW=function(){return this.state!==0};
mW.prototype.matches=function(D,O){return this.LW()&&D===this.uE&&O===this.qD};
rpR.prototype.reset=function(){this.timestamp=this.D=0};
eH.prototype.updateTime=function(D){for(var O=1;O<=15;++O)for(var h=1;h<=32;++h)this.j[O][h].timestamp=D};
eH.prototype.debugString=function(){for(var D="\n",O=1;O<=15;++O){for(var h=1;h<=32;++h){var V=this.j[O][h];D=V.D===0?D+"_":D+String.fromCharCode(V.D)}D+="\n"}return D};
eH.prototype.reset=function(D){for(var O=0;O<=15;O++)for(var h=0;h<=32;h++)this.j[O][h].reset();this.W=D;this.D=0;this.K=this.row=1};
var pW0=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],NZx=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],o$R=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Z2S=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];xRv.prototype.reset=function(D,O){this.J=O;this.style.set(2);this.K=this.Z;this.W=this.L;this.D=this.K;var h=(D<<2)+(O<<1);this.Z.reset(h);this.L.reset(h);this.text.reset((D<<2)+(O<<1)+1)};
TZc.prototype.reset=function(D){this.J=D;this.K.clear();this.W=this.j;this.j.reset(D,0);this.Z.reset(D,1)};OZc.prototype.W=function(){};g.e(ap,g.S4);ap.prototype.toString=function(){return g.S4.prototype.toString.call(this)};g.e(f$,g.n);f$.prototype.EN=function(){return[]};
f$.prototype.reset=function(){};g.e(K$,g.S4);K$.prototype.toString=function(){return g.S4.prototype.toString.call(this)};
var Ev=0;g.e(jH,f$);jH.prototype.reset=function(){this.Z={};this.K=this.D=null;this.J=!0};
jH.prototype.EN=function(D,O){D=D.firstChild;D.getAttribute("format");O=O||0;Number.isFinite(O);D=Array.from(D.childNodes);D=g.P(D);for(var h=D.next();!h.done;h=D.next())if(h=h.value,h.nodeType===1)switch(h.tagName){case "head":var V=h;break;case "body":var k=h}if(V)for(V=Array.from(V.childNodes),V=g.P(V),D=V.next();!D.done;D=V.next())if(D=D.value,D.nodeType===1)switch(D.tagName){case "pen":h=D.getAttribute("id");var C=this.pens,M={},c=D.getAttribute("p");c&&Object.assign(M,this.pens[c]);c=Am(D,"b");
c!=null&&(M.bold=c);c=Am(D,"i");c!=null&&(M.italic=c);c=Am(D,"u");c!=null&&(M.underline=c);c=Gw(D,"et");c!=null&&(M.charEdgeStyle=c);c=Gw(D,"of");c!=null&&(M.offset=c);c=vy(D,"bc");c!=null&&(M.background=c);c=vy(D,"ec");c!=null&&(M.aN=c);c=vy(D,"fc");c!=null&&(M.color=c);c=Gw(D,"fs");c!=null&&c!==0&&(M.fontFamily=c);c=Uv(D,"sz");c!==void 0&&(M.fontSizeIncrement=c/100-1);c=Uv(D,"bo");c!==void 0&&(M.backgroundOpacity=c/255);c=Uv(D,"fo");c!==void 0&&(M.textOpacity=c/255);c=Gw(D,"rb");c!=null&&c!==10&&
c!==0&&(M.zd=c>10?c-1:c);D=Gw(D,"hg");D!=null&&(M.Yp=D);C[h]=M;break;case "ws":h=D.getAttribute("id");this.T[h]=C3U(this,D);break;case "wp":h=D.getAttribute("id"),this.L[h]=MF_(this,D)}if(k){V=[];k=Array.from(k.childNodes);k=g.P(k);for(D=k.next();!D.done;D=k.next())if(D=D.value,D.nodeType===1)switch(D.tagName){case "w":this.D=bZS(this,D,O,!1);(D=this.Z[this.D.id])&&D.end>this.D.start&&(D.end=this.D.start);this.Z[this.D.id]=this.D;V.push(this.D);break;case "p":var S=D;c=O;h=[];C=S.getAttribute("w")||
this.W;M=!!Am(S,"a");c=(Uv(S,"t")||0)+c;var Y=Uv(S,"d")||5E3;M||(!this.J&&this.K&&this.K.windowId===C&&this.K.end>c&&(this.K.end=c),this.K&&this.K.text==="\n"&&(this.K.text=""));var J=M?6:5,q=S.getAttribute("p");q=q?this.pens[q]:null;var u=Array.from(S.childNodes);u.length&&(this.J=S.getAttribute("d")!=null);for(S=0;S<u.length;S++){var H=u[S],m=void 0;S>0&&(M=!0);var R=void 0;H.nodeType===1&&(R=H);if(R&&R.tagName==="s"){if((H=(H=R.getAttribute("p"))?this.pens[H]:null)&&H.zd&&(H.zd===1?(H=u.slice(S,
S+4),H.length===4&&(m=VFv(c,Y,C,M,J,H,this.pens),S+=3)):m=VFv(c,Y,C,M,J,[R],this.pens)),!m){var f=R;m=c;R=Y;H=C;var E=M,A=J,v=f.textContent?f.textContent:"",W=f.getAttribute("p");W=W?this.pens[W]:null;f=Uv(f,"t")||0;m=new ap(m+f,R-f,A,H,v,E,W)}}else m=new ap(c,Y,J,C,H.textContent||"",M,q);h.push(m);this.K=m}if(h.length>0)for(h[0].windowId===this.W&&(this.D=bZS(this,D,O,!0),V.push(this.D)),D=g.P(h),h=D.next();!h.done;h=D.next())h=h.value,h.windowId=this.D.id,this.D.D.push(h),V.push(h)}O=V}else O=[];
return O};var iZ_=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.e(QH,f$);QH.prototype.reset=function(){this.K.clear()};
QH.prototype.EN=function(D,O){var h=JSON.parse(D);if(!h)return[];if(h.pens){D=0;for(var V=g.P(h.pens),k=V.next();!k.done;k=V.next()){k=k.value;var C={},M=k.pParentId;M&&Object.assign(C,this.D.get(M));k.bAttr&&(C.bold=!0);k.iAttr&&(C.italic=!0);k.uAttr&&(C.underline=!0);M=k.ofOffset;M!=null&&(C.offset=M);k.szPenSize!==void 0&&(C.fontSizeIncrement=k.szPenSize/100-1);M=k.etEdgeType;M!=null&&(C.charEdgeStyle=M);k.ecEdgeColor!==void 0&&(C.aN=ww(k.ecEdgeColor));M=k.fsFontStyle;M!=null&&M!==0&&(C.fontFamily=
M);k.fcForeColor!==void 0&&(C.color=ww(k.fcForeColor));k.foForeAlpha!==void 0&&(C.textOpacity=k.foForeAlpha/255);k.bcBackColor!==void 0&&(C.background=ww(k.bcBackColor));k.boBackAlpha!==void 0&&(C.backgroundOpacity=k.boBackAlpha/255);(M=k.rbRuby)&&M!==10&&(C.zd=M>10?M-1:M,C.vl=iZ_.get(C.zd));k.hgHorizGroup&&(C.Yp=k.hgHorizGroup);this.D.set(D++,C)}}if(h.wsWinStyles)for(D=0,V=g.P(h.wsWinStyles),k=V.next();!k.done;k=V.next())k=k.value,C={},(M=k.wsParentId)?Object.assign(C,this.W.get(M)):Object.assign(C,
this.J),k.mhModeHint!==void 0&&(C.C5=k.mhModeHint),k.juJustifCode!==void 0&&(C.textAlign=k.juJustifCode),k.pdPrintDir!==void 0&&(C.T3=k.pdPrintDir),k.sdScrollDir!==void 0&&(C.tJ=k.sdScrollDir),k.wfcWinFillColor!==void 0&&(C.windowColor=ww(k.wfcWinFillColor)),k.wfoWinFillAlpha!==void 0&&(C.windowOpacity=k.wfoWinFillAlpha/255),this.W.set(D++,C);if(h.wpWinPositions)for(D=0,V=g.P(h.wpWinPositions),k=V.next();!k.done;k=V.next())k=k.value,C={},(M=k.wpParentId)&&Object.assign(C,this.j.get(M)),k.ahHorPos!==
void 0&&(C.k_=k.ahHorPos),k.apPoint!==void 0&&(C.zo=k.apPoint),k.avVerPos!==void 0&&(C.C3=k.avVerPos),k.ccCols!==void 0&&(C.cR=k.ccCols),k.rcRows!==void 0&&(C.dC=k.rcRows),this.j.set(D++,C);if(h.events){D=[];h=g.P(h.events);for(V=h.next();!V.done;V=h.next()){var c=V.value;k=(c.tStartMs||0)+O;C=c.dDurationMs||0;if(c.id)M=String(c.id),V=cJJ(this,c,k,C,M),D.push(V),this.K.set(M,V);else{c.wWinId?M=c.wWinId.toString():(M="_"+Ev++,V=cJJ(this,c,k,C,M),D.push(V),this.K.set(M,V));V=D;var S=c;C===0&&(C=5E3);
c=this.K.get(M);var Y=!!S.aAppend,J=Y?6:5,q=S.segs,u=null;S.pPenId&&(u=this.D.get(S.pPenId));for(S=0;S<q.length;S++){var H=q[S],m=H.utf8;if(m){var R=H.tOffsetMs||0,f=null;H.pPenId&&(f=this.D.get(H.pPenId));if((c.params.C5!=null?c.params.C5:c.D.length>1?1:0)===2&&Y&&m==="\n")continue;H=null;var E=[],A;if(A=f&&f.zd===1){A=q;var v=S;if(v+3>=A.length||!A[v+1].pPenId||!A[v+2].pPenId||!A[v+3].pPenId)A=!1;else{var W=A[v+1].pPenId;(W=this.D.get(W))&&W.zd&&W.zd===2?(W=A[v+2].pPenId,W=this.D.get(W),!W||!W.zd||
W.zd<3?A=!1:(W=A[v+3].pPenId,A=(W=this.D.get(W))&&W.zd&&W.zd===2?!0:!1)):A=!1}}if(A)R=q[S+1].utf8,H=q[S+3].utf8,A=q[S+2].utf8,v=this.D.get(q[S+2].pPenId),m=hoe(m,R,A,H,v),H=new ap(k,C,J,M,m,Y,f),S+=3;else{if(m.indexOf("<")>-1){var z=void 0;E=f;A=u;v=k;W=C;var X=R,Z=J,hd=Y,Yw=[],B=g.xl("<html>"+m+"</html>");if(!B.getElementsByTagName("parsererror").length&&((z=B.firstChild)==null?0:z.childNodes.length))for(z=g.P(B.firstChild.childNodes),B=z.next();!B.done;B=z.next()){B=B.value;var r=void 0,I=void 0,
L=(I=(r=B.textContent)==null?void 0:r.replace(/\n/g,""))!=null?I:"";if(B.nodeType!==3||L&&L.match(/^ *$/)==null){r={};Object.assign(r,E||A);I=void 0;switch((I=B)==null?void 0:I.tagName){case "b":r.bold=!0;break;case "i":r.italic=!0;break;case "u":r.underline=!0}Yw.push(new ap(v+X,W-X,Z,c.id,L,hd,r))}}E=Yw}E.length||(E=[new ap(k+R,C-R,J,c.id,m,Y,f||u)])}if(E.length)for(Y=g.P(E),f=Y.next();!f.done;f=Y.next())f=f.value,V.push(f),c.D.push(f);else H&&(V.push(H),c.D.push(H))}Y=!0}}}O=D}else O=[];return O};g.e(Wy,g.nu);Wy.prototype.mK=function(D,O,h){upC(this.videoData.videoId,D.vssId,h.bC)};
Wy.prototype.aU=function(D){if(this.audioTrack)for(var O=g.P(this.audioTrack.captionTracks),h=O.next();!h.done;h=O.next())g.zP(this.D,h.value);D.Yy()};g.e(Tw,qE);Tw.prototype.lj=function(D){var O=this.K.D;qE.prototype.lj.call(this,D);for(D=D.length;D<O.length;D++){var h=O[D];if(C&&h.D===k)var V=C;else{V={};Object.assign(V,h.D);Object.assign(V,rJe);var k=h.D;var C=V}WSL(this,h,V)}};
var rJe={qwF:!0};g.e(dw,OZc);dw.prototype.W=function(D,O,h,V,k){if(h<V){var C="_"+Ev++;h=h/1E3-this.Z;V=V/1E3-this.Z;D=new K$(h,V-h,5,C,{textAlign:0,zo:0,k_:O*2.5,C3:D*5.33});k=new ap(h,V-h,5,C,k);this.K.push(D);this.K.push(k)}};
g.e(Fr,f$);Fr.prototype.EN=function(D){D=new dw(D,D.byteLength,this.K);if(SLc(D)){for(;D.byteOffset<D.D.byteLength;)for(D.version===0?D.j=n$(D)*(1E3/45):D.version===1&&(D.j=n$(D)*4294967296+n$(D)),D.J=zw(D);D.J>0;D.J--){var O=zw(D),h=zw(D),V=zw(D);O&4&&(O&3)===this.track&&(this.track===0||this.track===1)&&(O=this.D,O.D.push({time:D.j,type:this.track,d4:h,R6:V,order:O.D.length}))}i28(this.D,D);return D.K}return[]};
Fr.prototype.reset=function(){this.D.clear()};g.e(yH,qE);g.b=yH.prototype;g.b.xU=function(){g.MZ(this.Vi)};
g.b.Ia7=function(){g.Hk(this.element,"ytp-rollup-mode");this.c_(this.bb,!0)};
g.b.Yt=function(){return this.j?this.Ew:this.U};
g.b.bH=function(){return this.j?this.U:this.Ew};
g.b.c_=function(D,O){this.bb=D;if(this.K.params.dC){for(var h=0,V=0;V<this.L.length&&h<D.length;V++)this.L[V]===D[h]&&h++;h>0&&h<D.length&&(D=this.L.concat(D.slice(h)));this.C1=this.Ew;this.U=this.Ew=0;qE.prototype.c_.call(this,D);u0R(this,O)}qE.prototype.c_.call(this,D)};g.e(HZ8,g.nu);g.b=HZ8.prototype;g.b.mK=function(D,O,h){var V=this;this.Hl();O=Lx9(this,D.getId());O||(O=D.languageCode,O=this.K.isManifestless?P3m(this,O,"386"):P3m(this,O));O&&(this.Z=D,this.L=O,this.j=function(k,C){mfv(V,k,h,C)},this.C.addEventListener("sabrCaptionsDataLoaded",this.j),this.C.publish("sabrCaptionsTrackChanged",g.VB(O.info,this.K.k5)))};
g.b.aU=function(D){var O=this.K.isManifestless?eom(this,"386"):eom(this);O=g.P(O);for(var h=O.next();!h.done;h=O.next())g.zP(this.D,h.value);D.Yy()};
g.b.Hl=function(){this.j!=null&&(this.C.removeEventListener("sabrCaptionsDataLoaded",this.j),this.j=null);this.Z=this.L=null;this.C.publish("sabrCaptionsTrackChanged",null)};
g.b.Aj=function(){return""};
g.b.eL=function(){this.C.Y8("captions")};g.e(is,f$);
is.prototype.EN=function(D,O){var h=[];D=D.split(pjJ);for(var V=1;V<D.length;V++){var k=D[V],C=O;if(k!==""&&!NjR.test(k)){var M=oeR.exec(k);if(M&&M.length>=4){var c=a9U(M[1]),S=a9U(M[2])-c;c+=C;var Y=(M=M[3])?M.split(" "):[];M={};var J=null;var q="";var u=null,H="";Y=g.P(Y);for(var m=Y.next();!m.done;m=Y.next())if(m=m.value.split(":"),m.length===2){var R=m[1];switch(m[0]){case "line":m=R.split(",");m[0].endsWith("%")&&(J=m[0],M.C3=Number.parseInt(J,10),m.length===2&&(q=m[1].trim()));break;case "position":m=
R.split(",");u=m[0];M.k_=Number.parseInt(u,10);m.length===2&&(H=m[1].trim());break;case "align":switch(R){case "start":M.textAlign=0;break;case "middle":M.textAlign=2;break;case "end":M.textAlign=1}}}J||q||(q="end");if(!u)switch(M.textAlign){case 0:M.k_=0;break;case 1:M.k_=100;break;case 2:M.k_=50}if(M.textAlign!=null){J=0;switch(q){case "center":J+=3;break;case "end":J+=6;break;default:J+=0}switch(H){case "line-left":J+=0;break;case "center":J+=1;break;case "line-right":J+=2;break;default:switch(M.textAlign){case 0:J+=
0;break;case 2:J+=1;break;case 1:J+=2}}q=J<0||J>8?7:J;M.zo=q}k=k.substring(oeR.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");H=M;M=k;k={};if(M.indexOf("<")<0&&M.indexOf("&")<0)C=f9x(c,S,5,H),S=new ap(c,S,5,C.id,M,!1,g.sO(k)?void 0:k),h.push(C),h.push(S),C.D.push(S);else for(q=M.split(ZZU),q.length===1?(M=5,H=f9x(c,S,M,H)):(J=M=6,H=Object.assign({cR:32},H),H=new K$(c,S,J,"_"+Ev++,H)),h.push(H),J=c,u=0;u<q.length;u++)Y=q[u],u%2===0?(m=g.xl("<html>"+Y+"</html>"),m.getElementsByTagName("parsererror").length?
(R=m.createElement("span"),R.appendChild(m.createTextNode(Y))):R=m.firstChild,Rov(this,J,S-(J-c),M,H,u>0,R,k,h)):J=a9U(Y)+C}oeR.lastIndex=0}}return h};
var NjR=/^NOTE/,pjJ=/(?:\r\n|\r|\n){2,}/,oeR=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),ZZU=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.NO.dg(is,{EN:"wvppt"});g.e(rw,g.n);
rw.prototype.EN=function(D,O,h,V){V=V||0;h=Eex(this,D,h||0);D=[];try{for(var k=g.P(h),C=k.next();!C.done;C=k.next()){var M=C.value,c=M.trackData,S=M.Bm;if(typeof c!=="string"){h=D;var Y=h.concat,J=O,q=c,u=S,H=V;if(!YLc(q))throw Error("Invalid binary caption track data");this.D||(this.D=new Fr(H,J));var m=this.D.EN(q,u);var R=Y.call(h,m)}else{if(c.substring(0,6)==="WEBVTT"){h=D;var f=h.concat;this.D||(this.D=new is);var E=this.D.EN(c,S);Math.random()<.01&&g.iZ(Error("Deprecated subtitles format in web player: WebVTT"));var A=
f.call(h,E)}else{h=D;var v=h.concat;a:{J=O;if(c[0]==="{")try{this.D||(this.D=new QH(jrC(J)));var W=this.D.EN(c,S);break a}catch(B){g.yK(B);W=[];break a}var z=g.xl(c);if(!z||!z.firstChild){var X=Error("Invalid caption track data");X.params=c;throw X;}if(z.firstChild.tagName==="timedtext"){if(Number(z.firstChild.getAttribute("format"))===3){q=z;this.D||(this.D=new jH(jrC(J),this.D8));W=this.D.EN(q,S);break a}var Z=Error("Unsupported subtitles format in web player (Format2)");Z.params=c;throw Z;}if(z.firstChild.tagName===
"transcript"){var hd=Error("Unsupported subtitles format in web player (Format1)");hd.params=c;throw hd;}var Yw=Error("Invalid caption track data");Yw.params=c;throw Yw;}A=v.call(h,W)}R=A}D=R}return D}catch(B){return this.logger.D(187101178,"Captions parsing failed: "+B.message+". "),this.clear(),[]}};
rw.prototype.clear=function(){this.D&&this.D.dispose();this.D=null};
rw.prototype.reset=function(){this.D&&this.D.reset()};
rw.prototype.fF=function(){g.n.prototype.fF.call(this);this.clear()};var $Q={windowColor:"#080808",windowOpacity:0,textAlign:2,zo:7,k_:50,C3:100,isDefault:!0,IK:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.e(p$,g.dX);g.b=p$.prototype;g.b.fF=function(){if(this.J||this.X1){var D=this.C.eg();D&&!D.Z8()&&D.bI()}else yJv(this,!1);g.dX.prototype.fF.call(this)};
g.b.bF=function(){return this.D8.S("html5_honor_caption_availabilities_in_audio_track")&&this.W!=="LIVE"&&this.W!=="SABR_LIVE"};
g.b.Bz=function(){if(this.Ax)return this.J||this.X1;var D=this.getAudioTrack();if(this.bF()){if(!D.captionTracks.length)return!1;if(!this.D)return!0}D=SOC(D,g.Z$(this.D8));return D==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:D==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?NE(this):tF_(this)||NE(this)?!0:ve9(this)};
g.b.load=function(){g.dX.prototype.load.call(this);this.U=this.getAudioTrack();if(this.D)this.K&&(this.T2.clear(),this.J?wj0(this,!0):this.player.getPresentingPlayerType()!==3&&this.D.mK(this.K,"json3",this.C1),this.J||this.X1||Xr(this)||this.player.VH("captionschanged",g.qv(this.K)));else{var D;this.W==="OFFLINE"?D=new Wy(this.player,this.videoData,this.getAudioTrack()):this.W==="SABR_LIVE"?D=new HZ8(this.videoData.D,this.player):this.W==="LIVE"?D=new Jm(this.videoData.D,this.player):this.W==="INNERTUBE"?
D=new g.FU(this.player,this.videoData,this.getAudioTrack()):D=new g.i9(this.player,this.videoData.RK,this.videoData.videoId,g.L7d(this.videoData),this.videoData.Ki,this.videoData.eventId);this.D=D;g.F(this,this.D);this.D.aU(this.C1)}};
g.b.unload=function(){this.J&&this.K?wj0(this,!1):(this.LF&&g.bY(this.LF),this.player.Y8("captions"),this.ME=[],this.D&&this.D.Hl(),this.T2.clear(),this.Ew&&this.player.nW(this.Ew),this.SM());g.dX.prototype.unload.call(this);this.player.M_();this.player.VH("captionschanged",{})};
g.b.create=function(){this.Bz()&&this.load();var D;a:{var O,h,V;if(this.D8.S("web_player_nitrate_promo_tooltip")&&((O=this.videoData.getPlayerResponse())==null?0:(h=O.captions)==null?0:(V=h.playerCaptionsTracklistRenderer)==null?0:V.enableTouchCaptionsNitrate)){var k,C;if(O=(D=this.videoData.getPlayerResponse())==null?void 0:(k=D.captions)==null?void 0:(C=k.playerCaptionsTracklistRenderer)==null?void 0:C.captionTracks)for(D=g.P(O),k=D.next();!k.done;k=D.next())if(k=k.value,k.kind==="asr"&&k.languageCode===
"en"){D=!0;break a}}D=!1}D&&this.C.publish("showpromotooltip",this.L.element)};
g.b.Yy=function(){var D=SOC(this.player.getAudioTrack(),g.Z$(this.D8));var O=D==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?Z5(this,this.T):D==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&NE(this)?op(this):tF_(this)||this.T||ve9(this)?Z5(this,this.T):NE(this)?op(this):null;if(this.J||this.X1){var h=g.E7(this.D.D,!0);D=[];for(var V=0;V<h.length;V++){var k=h[V],C=g.CZ("TRACK");C.setAttribute("kind","subtitles");C.setAttribute("label",g.J1(k));C.setAttribute("srclang",g.uE(k));C.setAttribute("id",k.toString());
this.X1||C.setAttribute("src",this.D.Aj(k,"vtt"));k===O&&C.setAttribute("default","1");D.push(C)}O=this.C.eg();O.H7(D);D=O.JU();this.yy&&this.qE.G(D.textTracks,"change",this.N05)}else!this.K&&O&&xQ(this,O),this.player.VH("onCaptionsTrackListChanged"),this.player.Mr("onApiChange")};
g.b.N05=function(){for(var D=this.C.eg().JU().textTracks,O=null,h=0;h<D.length;h++)if(D[h].mode==="showing")a:{O=g.E7(this.D.D,!0);for(var V=0;V<O.length;V++)if(O[V].toString()===D[h].id){O=O[V];break a}O=null}(this.loaded?this.K:null)!==O&&xQ(this,O,!0)};
g.b.Zm1=function(){!this.K&&this.J||this.unload()};
g.b.bC=function(D,O,h,V){if(D){var k;Wx8(this,(k=this.K)!=null?k:void 0);this.D.du()&&(this.ME=[],this.C.Y8("captions"),SH(this.ST),this.T2.reset());if(this.videoData.UW){var C;h=((C=h)!=null?C:0)+this.videoData.UW}D=this.T2.EN(D,O,h,V);if(this.oW)for(O=g.P(D),h=O.next();!h.done;h=O.next())h=h.value,h.j=this.videoData.clientPlaybackNonce,h.x0=this.videoData.UW;O=!this.D8.S("html5_keep_caption_data_after_seek")&&(this.W==="LIVE"||this.W==="SABR_LIVE");this.player.nW(D,void 0,O);!this.T||this.X1||Xr(this)||
!this.D8.UY||g.wq(this.D8)||g.wO(this.D8)||g.pP(this.D8)||this.D8.ME==="shortspage"||this.player.isInline()||(g.bY(this.LF),D=kG8({zo:0,k_:5,C3:5,dC:2,textAlign:0,T3:0,lang:"en-GB"}),this.G2=[D],O=["Click "," for settings"],this.m5||(h=new g.eg(g.WG()),g.F(this,h),this.m5=h.element),h=D.end-D.start,(V=g.J1(this.K))&&this.G2.push(new ap(D.start,h,0,D.id,V)),this.G2.push(new ap(D.start,h,0,D.id,O[0]),new ap(D.start,h,0,D.id,this.m5,!0),new ap(D.start,h,0,D.id,O[1],!0)),this.player.nW(this.G2),g.Cd(this.LF));
!this.T||this.X1||Xr(this)||(g.Z$(this.D8)?By(this,!0):ls(this,!0),this.U&&(this.U.W=this.K),this.player.M_());this.T=!1}};
g.b.onCueRangeEnter=function(D){this.ME.push(D);SH(this.ST)};
g.b.onCueRangeExit=function(D){g.xC(this.ME,D);this.D instanceof Jm&&this.D.L&&this.player.FD([D]);SH(this.ST)};
g.b.getCaptionWindowContainerId=function(){return this.L.element.id};
g.b.oGw=function(){Fxm(this,this.G2);this.G2=null};
g.b.Xy=function(){var D=this;if(!this.f1||!this.J){this.ST.stop();g.Ztq(this.Vi);this.ME.sort(g.Y8);var O=this.ME;if(this.Ew){var h=g.LS(O,function(C){return this.Ew.indexOf(C)===-1},this);
h.length&&(O=h)}O=g.P(O);for(h=O.next();!h.done;h=O.next())dfC(this,h.value);O=g.P(Object.entries(this.lS));var V=O.next();for(h={};!V.done;h={Yv:void 0,AX:void 0},V=O.next()){var k=g.P(V.value);V=k.next().value;k=k.next().value;h.Yv=V;h.AX=k;this.Vi[h.Yv]?(h.AX.element.parentNode||(h.AX instanceof yH||h.AX instanceof Tw||g.UO(this.lS,function(C){return function(M,c){c!==C.Yv&&M.K.params.zo===C.AX.K.params.zo&&M.K.params.k_===C.AX.K.params.k_&&M.K.params.C3===C.AX.K.params.C3&&(M.dispose(),delete D.lS[c]);
return c===C.Yv}}(h),this),this.L.element.appendChild(h.AX.element)),h.AX.c_(this.Vi[h.Yv])):(h.AX.dispose(),delete this.lS[h.Yv])}}};
g.b.mri=function(){AJx(this,{},!0);this.player.VH("captionssettingschanged")};
g.b.e7=function(){var D=$Q.IK;D={background:D.background,backgroundOpacity:D.backgroundOpacity,charEdgeStyle:D.charEdgeStyle,color:D.color,fontFamily:D.fontFamily,fontSizeIncrement:D.fontSizeIncrement,fontStyle:D.bold&&D.italic?3:D.bold?1:D.italic?2:0,textOpacity:D.textOpacity,windowColor:$Q.windowColor,windowOpacity:$Q.windowOpacity};var O=Ple()||{};O.background!=null&&(D.background=O.background);O.backgroundOverride!=null&&(D.backgroundOverride=O.backgroundOverride);O.backgroundOpacity!=null&&(D.backgroundOpacity=
O.backgroundOpacity);O.backgroundOpacityOverride!=null&&(D.backgroundOpacityOverride=O.backgroundOpacityOverride);O.charEdgeStyle!=null&&(D.charEdgeStyle=O.charEdgeStyle);O.charEdgeStyleOverride!=null&&(D.charEdgeStyleOverride=O.charEdgeStyleOverride);O.color!=null&&(D.color=O.color);O.colorOverride!=null&&(D.colorOverride=O.colorOverride);O.fontFamily!=null&&(D.fontFamily=O.fontFamily);O.fontFamilyOverride!=null&&(D.fontFamilyOverride=O.fontFamilyOverride);O.fontSizeIncrement!=null&&(D.fontSizeIncrement=
O.fontSizeIncrement);O.fontSizeIncrementOverride!=null&&(D.fontSizeIncrementOverride=O.fontSizeIncrementOverride);O.fontStyle!=null&&(D.fontStyle=O.fontStyle);O.fontStyleOverride!=null&&(D.fontStyleOverride=O.fontStyleOverride);O.textOpacity!=null&&(D.textOpacity=O.textOpacity);O.textOpacityOverride!=null&&(D.textOpacityOverride=O.textOpacityOverride);O.windowColor!=null&&(D.windowColor=O.windowColor);O.windowColorOverride!=null&&(D.windowColorOverride=O.windowColorOverride);O.windowOpacity!=null&&
(D.windowOpacity=O.windowOpacity);O.windowOpacityOverride!=null&&(D.windowOpacityOverride=O.windowOpacityOverride);return D};
g.b.I8=function(D,O){var h={};Object.assign(h,Ple());Object.assign(h,D);AJx(this,h,O);this.player.VH("captionssettingschanged")};
g.b.SM=function(){!this.J&&this.loaded&&(g.K2(this.lS,function(D,O){D.dispose();delete this.lS[O]},this),this.Xy())};
g.b.mG=function(D,O){switch(D){case "fontSize":if(isNaN(O))break;D=g.mS(O,-2,4);this.I8({fontSizeIncrement:D});return D;case "reload":O&&!this.J&&xQ(this,this.K,!0);break;case "stickyLoading":O!==void 0&&this.D8.L&&(g.Z$(this.D8)?By(this,!!O):ls(this,!!O));break;case "track":return nev(this,O);case "tracklist":return this.D?g.WS(g.E7(this.D.D,!(!O||!O.includeAsr)),function(h){return g.qv(h)}):[];
case "translationLanguages":return this.D?this.D.J.map(function(h){return Object.assign({},h)}):[];
case "sampleSubtitles":this.J||O===void 0||yJv(this,!!O);break;case "sampleSubtitlesCustomized":this.J||yJv(this,!!O,O);break;case "recommendedTranslationLanguages":return g.ix();case "defaultTranslationSourceTrackIndices":return this.D?this.D.T:[]}};
g.b.getOptions=function(){var D="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.D8.L&&D.push("stickyLoading");return D};
g.b.VX=function(){var D=this.K;if(this.C.Fs("captions")){if(this.D8.S("html5_modify_caption_vss_logging")){var O;return(D=(O=this.videoData.mf)!=null?O:null)?{cc:g.AsB(D)}:{}}if(D)return O=D.vssId,D.translationLanguage&&O&&(O="t"+O+"."+g.uE(D)),{cc:O}}return{}};
g.b.unT=function(){this.isSubtitlesOn()?(g.Z$(this.D8)?By(this,!1):ls(this,!1),Wx8(this),this.D8.S("html5_report_caption_format_change")?xQ(this,null,!0):(this.unload(),NE(this,!0)&&xQ(this,op(this),!1))):this.xA()};
g.b.xA=function(){var D=Xr(this)||!this.K?Z5(this,!0):this.K;this.D8.S("html5_report_caption_format_intent")&&D&&this.V8(D.vssId,"m");this.isSubtitlesOn()||xQ(this,Xr(this)||!this.K?Z5(this,!0):this.K,!0)};
g.b.isSubtitlesOn=function(){return!!this.loaded&&!!this.K&&!Xr(this)};
g.b.kqr=function(){var D=Xr(this);NE(this,D)?xQ(this,this.getAudioTrack().D,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.bF()&&(this.T=!1,this.K=null,this.D&&(this.D.dispose(),this.D=null)),this.Bz()&&(D?xQ(this,Z5(this,!1),!1):this.load()))};
g.b.Ak=function(D){D&&(this.jT={top:D.top,right:D.right,bottom:D.bottom,left:D.left,width:1-D.left-D.right,height:1-D.top-D.bottom},this.L.element.style.top=this.jT.top*100+"%",this.L.element.style.left=this.jT.left*100+"%",this.L.element.style.width=this.jT.width*100+"%",this.L.element.style.height=this.jT.height*100+"%",this.L.element.style.position="absolute",D=zoR(this))&&(this.L.element.style.width=D.width+"px",this.L.element.style.height=D.height+"px")};
g.b.onVideoDataChange=function(D,O){D==="newdata"&&(this.videoData=O,this.loaded&&this.unload(),this.T=!1,this.K=null,this.D&&(this.D.dispose(),this.D=null,this.player.VH("captionschanged",{})),this.Bz()&&this.load())};
g.b.getAudioTrack=function(){return this.oW&&this.player.getPresentingPlayerType()===2?this.videoData.Kd:this.player.getAudioTrack()};
g.b.XFF=function(){var D=this.C.eg();D&&!D.Z8()&&D.bI();this.C.isFullscreen()?(this.J=this.Ax=!0,this.loaded&&this.Yy()):(this.Ax=this.D8.controlsType==="3",this.J=UfJ(this));xQ(this,this.K)};
g.b.WL=function(){var D,O,h,V=(D=this.videoData.getPlayerResponse())==null?void 0:(O=D.captions)==null?void 0:(h=O.playerCaptionsTracklistRenderer)==null?void 0:h.openTranscriptCommand;V&&this.player.F1("innertubeCommand",V)};
g.b.o0=function(D,O,h){var V=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,k="";D&&(k=D.vssId,k=k.replace(V,""));var C="";D&&D.getId()&&(C=D.getId()||"");D&&D.getXtags()&&(D=D.getXtags(),D=D.replace(V,""),C=C.concat(";"+D));this.C.o0(O?k:"",O?C:"",h)};
g.b.V8=function(D,O){D=(D||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");D.length>0&&this.C.V8(D,O)};
g.b.eL=function(){this.D&&this.D.eL()};
g.NO.dg(p$,{Xy:"smucd"});g.TP("captions",p$);})(_yt_player);
